-- AlterEnum: orígenes de campaña por isapre / Isapres Premium
ALTER TYPE "ClientOrigin" ADD VALUE IF NOT EXISTS 'CAMPANA_ISAPRES_PREMIUM';
ALTER TYPE "ClientOrigin" ADD VALUE IF NOT EXISTS 'CAMPANA_CONSALUD';
ALTER TYPE "ClientOrigin" ADD VALUE IF NOT EXISTS 'CAMPANA_BANMEDICA';
ALTER TYPE "ClientOrigin" ADD VALUE IF NOT EXISTS 'CAMPANA_COLMENA';
ALTER TYPE "ClientOrigin" ADD VALUE IF NOT EXISTS 'CAMPANA_CRUZ_BLANCA';
ALTER TYPE "ClientOrigin" ADD VALUE IF NOT EXISTS 'CAMPANA_VIDA_TRES';
ALTER TYPE "ClientOrigin" ADD VALUE IF NOT EXISTS 'CAMPANA_NUEVA_MASVIDA';
ALTER TYPE "ClientOrigin" ADD VALUE IF NOT EXISTS 'CAMPANA_ESENCIAL';
