// This file is auto-generated by a script. Do not edit manually.
export interface AgreementPlanMapping {
  code: string;
  price: number;
  originalPrice: number | null;
}

export const AGREEMENT_PLAN_MAPPINGS: Record<string, Record<string, AgreementPlanMapping>> = {
  "colmena": {
    "12038": {
      "code": "12067",
      "price": 1.56,
      "originalPrice": 1.76
    },
    "12039": {
      "code": "12068",
      "price": 1.72,
      "originalPrice": 1.93
    },
    "12040": {
      "code": "12069",
      "price": 1.87,
      "originalPrice": 2.11
    },
    "12041": {
      "code": "12070",
      "price": 2.03,
      "originalPrice": 2.28
    },
    "12042": {
      "code": "12071",
      "price": 2.17,
      "originalPrice": 2.43
    },
    "12043": {
      "code": "12072",
      "price": 1.87,
      "originalPrice": 2.1
    },
    "12044": {
      "code": "12073",
      "price": 2.03,
      "originalPrice": 2.28
    },
    "12045": {
      "code": "12074",
      "price": 2.18,
      "originalPrice": 2.45
    },
    "12046": {
      "code": "12075",
      "price": 2.31,
      "originalPrice": 2.6
    },
    "12047": {
      "code": "12076",
      "price": 2.02,
      "originalPrice": 2.27
    },
    "12048": {
      "code": "12077",
      "price": 2.18,
      "originalPrice": 2.45
    },
    "12049": {
      "code": "12078",
      "price": 2.33,
      "originalPrice": 2.62
    },
    "12050": {
      "code": "12079",
      "price": 2.47,
      "originalPrice": 2.77
    },
    "12051": {
      "code": "12080",
      "price": 2.16,
      "originalPrice": 2.43
    },
    "12052": {
      "code": "12081",
      "price": 2.33,
      "originalPrice": 2.62
    },
    "12053": {
      "code": "12082",
      "price": 2.49,
      "originalPrice": 2.79
    },
    "12054": {
      "code": "12083",
      "price": 2.62,
      "originalPrice": 2.94
    },
    "12055": {
      "code": "12084",
      "price": 2.4,
      "originalPrice": 2.69
    },
    "12056": {
      "code": "12085",
      "price": 2.57,
      "originalPrice": 2.88
    },
    "12057": {
      "code": "12086",
      "price": 2.73,
      "originalPrice": 3.06
    },
    "12058": {
      "code": "12087",
      "price": 2.86,
      "originalPrice": 3.21
    },
    "12059": {
      "code": "12088",
      "price": 2.54,
      "originalPrice": 2.85
    },
    "12060": {
      "code": "12089",
      "price": 2.72,
      "originalPrice": 3.05
    },
    "12061": {
      "code": "12090",
      "price": 2.87,
      "originalPrice": 3.22
    },
    "12062": {
      "code": "12091",
      "price": 3.03,
      "originalPrice": 3.39
    },
    "12063": {
      "code": "12092",
      "price": 2.65,
      "originalPrice": 2.97
    },
    "12064": {
      "code": "12093",
      "price": 2.84,
      "originalPrice": 3.18
    },
    "12065": {
      "code": "12094",
      "price": 3.01,
      "originalPrice": 3.37
    },
    "12066": {
      "code": "12095",
      "price": 3.15,
      "originalPrice": 3.53
    },
    "12096": {
      "code": "12125",
      "price": 1.61,
      "originalPrice": 1.82
    },
    "12097": {
      "code": "12126",
      "price": 1.77,
      "originalPrice": 2
    },
    "12098": {
      "code": "12127",
      "price": 1.95,
      "originalPrice": 2.19
    },
    "12099": {
      "code": "12128",
      "price": 2.11,
      "originalPrice": 2.37
    },
    "12100": {
      "code": "12129",
      "price": 2.25,
      "originalPrice": 2.53
    },
    "12101": {
      "code": "12130",
      "price": 1.94,
      "originalPrice": 2.18
    },
    "12102": {
      "code": "12131",
      "price": 2.12,
      "originalPrice": 2.38
    },
    "12103": {
      "code": "12132",
      "price": 2.28,
      "originalPrice": 2.56
    },
    "12104": {
      "code": "12133",
      "price": 2.42,
      "originalPrice": 2.72
    },
    "12105": {
      "code": "12134",
      "price": 2.11,
      "originalPrice": 2.37
    },
    "12106": {
      "code": "12135",
      "price": 2.28,
      "originalPrice": 2.56
    },
    "12107": {
      "code": "12136",
      "price": 2.44,
      "originalPrice": 2.74
    },
    "12108": {
      "code": "12137",
      "price": 2.59,
      "originalPrice": 2.91
    },
    "12109": {
      "code": "12138",
      "price": 2.27,
      "originalPrice": 2.55
    },
    "12110": {
      "code": "12139",
      "price": 2.45,
      "originalPrice": 2.75
    },
    "12111": {
      "code": "12140",
      "price": 2.61,
      "originalPrice": 2.93
    },
    "12112": {
      "code": "12141",
      "price": 2.76,
      "originalPrice": 3.1
    },
    "12113": {
      "code": "12142",
      "price": 2.43,
      "originalPrice": 2.73
    },
    "12114": {
      "code": "12143",
      "price": 2.61,
      "originalPrice": 2.93
    },
    "12115": {
      "code": "12144",
      "price": 2.78,
      "originalPrice": 3.12
    },
    "12116": {
      "code": "12145",
      "price": 2.94,
      "originalPrice": 3.29
    },
    "12117": {
      "code": "12146",
      "price": 2.59,
      "originalPrice": 2.91
    },
    "12118": {
      "code": "12147",
      "price": 2.77,
      "originalPrice": 3.11
    },
    "12119": {
      "code": "12148",
      "price": 2.94,
      "originalPrice": 3.3
    },
    "12120": {
      "code": "12149",
      "price": 3.1,
      "originalPrice": 3.47
    },
    "12121": {
      "code": "12150",
      "price": 2.72,
      "originalPrice": 3.05
    },
    "12122": {
      "code": "12151",
      "price": 2.91,
      "originalPrice": 3.26
    },
    "12123": {
      "code": "12152",
      "price": 3.08,
      "originalPrice": 3.45
    },
    "12124": {
      "code": "12153",
      "price": 3.23,
      "originalPrice": 3.62
    },
    "12410": {
      "code": "12439",
      "price": 1.52,
      "originalPrice": 1.72
    },
    "12411": {
      "code": "12440",
      "price": 1.59,
      "originalPrice": 1.79
    },
    "12412": {
      "code": "12441",
      "price": 1.68,
      "originalPrice": 1.89
    },
    "12413": {
      "code": "12442",
      "price": 1.79,
      "originalPrice": 2.02
    },
    "12414": {
      "code": "12443",
      "price": 1.99,
      "originalPrice": 2.24
    },
    "12415": {
      "code": "12444",
      "price": 1.7,
      "originalPrice": 1.92
    },
    "12416": {
      "code": "12445",
      "price": 1.81,
      "originalPrice": 2.04
    },
    "12417": {
      "code": "12446",
      "price": 1.9,
      "originalPrice": 2.14
    },
    "12418": {
      "code": "12447",
      "price": 2.09,
      "originalPrice": 2.35
    },
    "12419": {
      "code": "12448",
      "price": 1.82,
      "originalPrice": 2.05
    },
    "12420": {
      "code": "12449",
      "price": 1.89,
      "originalPrice": 2.13
    },
    "12421": {
      "code": "12450",
      "price": 2.02,
      "originalPrice": 2.27
    },
    "12422": {
      "code": "12451",
      "price": 2.19,
      "originalPrice": 2.46
    },
    "12423": {
      "code": "12452",
      "price": 1.94,
      "originalPrice": 2.18
    },
    "12424": {
      "code": "12453",
      "price": 2.05,
      "originalPrice": 2.31
    },
    "12425": {
      "code": "12454",
      "price": 2.17,
      "originalPrice": 2.44
    },
    "12426": {
      "code": "12455",
      "price": 2.28,
      "originalPrice": 2.56
    },
    "12427": {
      "code": "12456",
      "price": 2.04,
      "originalPrice": 2.29
    },
    "12428": {
      "code": "12457",
      "price": 2.15,
      "originalPrice": 2.42
    },
    "12429": {
      "code": "12458",
      "price": 2.27,
      "originalPrice": 2.55
    },
    "12430": {
      "code": "12459",
      "price": 2.38,
      "originalPrice": 2.67
    },
    "12431": {
      "code": "12460",
      "price": 2.15,
      "originalPrice": 2.42
    },
    "12432": {
      "code": "12461",
      "price": 2.27,
      "originalPrice": 2.55
    },
    "12433": {
      "code": "12462",
      "price": 2.4,
      "originalPrice": 2.69
    },
    "12434": {
      "code": "12463",
      "price": 2.69,
      "originalPrice": 3.02
    },
    "12468": {
      "code": "12489",
      "price": 1.46,
      "originalPrice": 1.65
    },
    "12469": {
      "code": "12490",
      "price": 1.49,
      "originalPrice": 1.68
    },
    "12470": {
      "code": "12491",
      "price": 1.51,
      "originalPrice": 1.71
    },
    "12471": {
      "code": "12492",
      "price": 1.53,
      "originalPrice": 1.73
    },
    "12472": {
      "code": "12493",
      "price": 1.58,
      "originalPrice": 1.78
    },
    "12473": {
      "code": "12494",
      "price": 1.62,
      "originalPrice": 1.83
    },
    "12474": {
      "code": "12495",
      "price": 1.65,
      "originalPrice": 1.86
    },
    "12475": {
      "code": "12496",
      "price": 1.72,
      "originalPrice": 1.94
    },
    "12476": {
      "code": "12497",
      "price": 1.78,
      "originalPrice": 2
    },
    "12477": {
      "code": "12498",
      "price": 1.8,
      "originalPrice": 2.03
    },
    "12478": {
      "code": "12499",
      "price": 1.87,
      "originalPrice": 2.1
    },
    "12479": {
      "code": "12500",
      "price": 2,
      "originalPrice": 2.25
    },
    "12480": {
      "code": "12501",
      "price": 2.05,
      "originalPrice": 2.3
    },
    "12481": {
      "code": "12502",
      "price": 2.23,
      "originalPrice": 2.5
    },
    "12482": {
      "code": "12503",
      "price": 2.45,
      "originalPrice": 2.75
    },
    "12483": {
      "code": "12504",
      "price": 2.68,
      "originalPrice": 3
    },
    "12484": {
      "code": "12505",
      "price": 2.81,
      "originalPrice": 3.15
    },
    "12485": {
      "code": "12506",
      "price": 2.9,
      "originalPrice": 3.25
    },
    "12486": {
      "code": "12507",
      "price": 2.72,
      "originalPrice": 3.05
    },
    "12487": {
      "code": "12508",
      "price": 2.86,
      "originalPrice": 3.2
    },
    "12488": {
      "code": "12509",
      "price": 2.99,
      "originalPrice": 3.35
    },
    "12510": {
      "code": "12542",
      "price": 1.08,
      "originalPrice": 1.2
    },
    "12511": {
      "code": "12543",
      "price": 1.1,
      "originalPrice": 1.22
    },
    "12512": {
      "code": "12544",
      "price": 1.12,
      "originalPrice": 1.24
    },
    "12513": {
      "code": "12545",
      "price": 1.1,
      "originalPrice": 1.22
    },
    "12514": {
      "code": "12546",
      "price": 1.12,
      "originalPrice": 1.24
    },
    "12515": {
      "code": "12547",
      "price": 1.13,
      "originalPrice": 1.26
    },
    "12516": {
      "code": "12548",
      "price": 1.11,
      "originalPrice": 1.23
    },
    "12517": {
      "code": "12549",
      "price": 1.13,
      "originalPrice": 1.25
    },
    "12518": {
      "code": "12550",
      "price": 1.17,
      "originalPrice": 1.3
    },
    "12519": {
      "code": "12551",
      "price": 1.24,
      "originalPrice": 1.38
    },
    "12520": {
      "code": "12552",
      "price": 1.33,
      "originalPrice": 1.48
    },
    "12521": {
      "code": "12553",
      "price": 1.38,
      "originalPrice": 1.53
    },
    "12522": {
      "code": "12554",
      "price": 1.24,
      "originalPrice": 1.38
    },
    "12523": {
      "code": "12555",
      "price": 1.32,
      "originalPrice": 1.47
    },
    "12524": {
      "code": "12556",
      "price": 1.4,
      "originalPrice": 1.55
    },
    "12525": {
      "code": "12557",
      "price": 1.44,
      "originalPrice": 1.6
    },
    "12526": {
      "code": "12558",
      "price": 1.31,
      "originalPrice": 1.45
    },
    "12527": {
      "code": "12559",
      "price": 1.39,
      "originalPrice": 1.54
    },
    "12528": {
      "code": "12560",
      "price": 1.46,
      "originalPrice": 1.62
    },
    "12529": {
      "code": "12561",
      "price": 1.51,
      "originalPrice": 1.68
    },
    "12530": {
      "code": "12562",
      "price": 1.37,
      "originalPrice": 1.52
    },
    "12531": {
      "code": "12563",
      "price": 1.45,
      "originalPrice": 1.61
    },
    "12532": {
      "code": "12564",
      "price": 1.74,
      "originalPrice": 1.93
    },
    "12533": {
      "code": "12565",
      "price": 1.78,
      "originalPrice": 1.98
    },
    "12534": {
      "code": "12566",
      "price": 1.58,
      "originalPrice": 1.76
    },
    "12535": {
      "code": "12567",
      "price": 1.69,
      "originalPrice": 1.88
    },
    "12536": {
      "code": "12568",
      "price": 1.78,
      "originalPrice": 1.98
    },
    "12537": {
      "code": "12569",
      "price": 1.83,
      "originalPrice": 2.03
    },
    "12538": {
      "code": "12570",
      "price": 1.64,
      "originalPrice": 1.82
    },
    "12539": {
      "code": "12571",
      "price": 1.75,
      "originalPrice": 1.94
    },
    "12540": {
      "code": "12572",
      "price": 1.83,
      "originalPrice": 2.03
    },
    "12541": {
      "code": "12573",
      "price": 1.91,
      "originalPrice": 2.12
    },
    "12828": {
      "code": "12846",
      "price": 1.5,
      "originalPrice": 1.67
    },
    "12829": {
      "code": "12847",
      "price": 1.63,
      "originalPrice": 1.81
    },
    "12830": {
      "code": "12848",
      "price": 1.73,
      "originalPrice": 1.92
    },
    "12831": {
      "code": "12849",
      "price": 1.77,
      "originalPrice": 1.97
    },
    "12832": {
      "code": "12850",
      "price": 1.87,
      "originalPrice": 2.08
    },
    "12833": {
      "code": "12851",
      "price": 1.95,
      "originalPrice": 2.17
    },
    "12834": {
      "code": "12852",
      "price": 1.91,
      "originalPrice": 2.12
    },
    "12835": {
      "code": "12853",
      "price": 2.02,
      "originalPrice": 2.24
    },
    "12836": {
      "code": "12854",
      "price": 2.11,
      "originalPrice": 2.34
    },
    "12837": {
      "code": "12855",
      "price": 2.05,
      "originalPrice": 2.28
    },
    "12838": {
      "code": "12856",
      "price": 2.26,
      "originalPrice": 2.51
    },
    "12839": {
      "code": "12857",
      "price": 2.81,
      "originalPrice": 3.12
    },
    "12840": {
      "code": "12858",
      "price": 2.88,
      "originalPrice": 3.2
    },
    "12841": {
      "code": "12859",
      "price": 3,
      "originalPrice": 3.33
    },
    "12842": {
      "code": "12860",
      "price": 3.1,
      "originalPrice": 3.44
    },
    "12843": {
      "code": "12861",
      "price": 3.46,
      "originalPrice": 3.84
    },
    "12844": {
      "code": "12862",
      "price": 3.82,
      "originalPrice": 4.24
    },
    "12845": {
      "code": "12863",
      "price": 4.18,
      "originalPrice": 4.64
    },
    "12864": {
      "code": "12905",
      "price": 1.16,
      "originalPrice": 1.29
    },
    "12865": {
      "code": "12906",
      "price": 1.2,
      "originalPrice": 1.33
    },
    "12866": {
      "code": "12907",
      "price": 1.26,
      "originalPrice": 1.4
    },
    "12867": {
      "code": "12908",
      "price": 1.3,
      "originalPrice": 1.44
    },
    "12868": {
      "code": "12909",
      "price": 1.33,
      "originalPrice": 1.48
    },
    "12869": {
      "code": "12910",
      "price": 1.37,
      "originalPrice": 1.52
    },
    "12870": {
      "code": "12911",
      "price": 1.39,
      "originalPrice": 1.54
    },
    "12871": {
      "code": "12912",
      "price": 1.43,
      "originalPrice": 1.59
    },
    "12872": {
      "code": "12913",
      "price": 1.48,
      "originalPrice": 1.64
    },
    "12873": {
      "code": "12914",
      "price": 1.53,
      "originalPrice": 1.7
    },
    "12874": {
      "code": "12915",
      "price": 1.55,
      "originalPrice": 1.72
    },
    "12875": {
      "code": "12916",
      "price": 1.58,
      "originalPrice": 1.76
    },
    "12876": {
      "code": "12917",
      "price": 1.86,
      "originalPrice": 2.07
    },
    "12877": {
      "code": "12918",
      "price": 2.03,
      "originalPrice": 2.25
    },
    "12878": {
      "code": "12919",
      "price": 2.09,
      "originalPrice": 2.32
    },
    "12879": {
      "code": "12920",
      "price": 1.94,
      "originalPrice": 2.16
    },
    "12880": {
      "code": "12921",
      "price": 2.12,
      "originalPrice": 2.35
    },
    "12881": {
      "code": "12922",
      "price": 2.25,
      "originalPrice": 2.5
    },
    "12882": {
      "code": "12923",
      "price": 2.3,
      "originalPrice": 2.56
    },
    "12883": {
      "code": "12924",
      "price": 2.47,
      "originalPrice": 2.74
    },
    "12884": {
      "code": "12925",
      "price": 2.79,
      "originalPrice": 3.1
    },
    "12885": {
      "code": "12926",
      "price": 2.93,
      "originalPrice": 3.25
    },
    "12886": {
      "code": "12927",
      "price": 3.06,
      "originalPrice": 3.4
    },
    "12887": {
      "code": "12928",
      "price": 3.02,
      "originalPrice": 3.35
    },
    "12888": {
      "code": "12929",
      "price": 3.11,
      "originalPrice": 3.45
    },
    "12889": {
      "code": "12930",
      "price": 3.2,
      "originalPrice": 3.55
    },
    "12890": {
      "code": "12931",
      "price": 3.33,
      "originalPrice": 3.7
    },
    "12891": {
      "code": "12932",
      "price": 3.41,
      "originalPrice": 3.79
    },
    "12892": {
      "code": "12933",
      "price": 3.49,
      "originalPrice": 3.88
    },
    "12893": {
      "code": "12934",
      "price": 3.57,
      "originalPrice": 3.97
    },
    "12894": {
      "code": "12935",
      "price": 3.65,
      "originalPrice": 4.06
    },
    "12895": {
      "code": "12936",
      "price": 3.74,
      "originalPrice": 4.15
    },
    "12896": {
      "code": "12937",
      "price": 3.82,
      "originalPrice": 4.24
    },
    "12897": {
      "code": "12938",
      "price": 3.9,
      "originalPrice": 4.33
    },
    "12898": {
      "code": "12939",
      "price": 3.98,
      "originalPrice": 4.42
    },
    "12899": {
      "code": "12940",
      "price": 4.06,
      "originalPrice": 4.51
    },
    "12900": {
      "code": "12941",
      "price": 4.14,
      "originalPrice": 4.6
    },
    "12901": {
      "code": "12942",
      "price": 4.22,
      "originalPrice": 4.69
    },
    "12902": {
      "code": "12943",
      "price": 4.3,
      "originalPrice": 4.78
    },
    "12903": {
      "code": "12944",
      "price": 4.38,
      "originalPrice": 4.87
    },
    "12904": {
      "code": "12945",
      "price": 4.46,
      "originalPrice": 4.96
    },
    "13001": {
      "code": "13002",
      "price": 4.54,
      "originalPrice": 5.04
    },
    "13003": {
      "code": "13019",
      "price": 2.83,
      "originalPrice": 3.14
    },
    "13004": {
      "code": "13020",
      "price": 3.01,
      "originalPrice": 3.34
    },
    "13005": {
      "code": "13021",
      "price": 3.19,
      "originalPrice": 3.54
    },
    "13006": {
      "code": "13022",
      "price": 3.32,
      "originalPrice": 3.69
    },
    "13007": {
      "code": "13023",
      "price": 3.01,
      "originalPrice": 3.34
    },
    "13008": {
      "code": "13024",
      "price": 3.19,
      "originalPrice": 3.54
    },
    "13009": {
      "code": "13025",
      "price": 3.37,
      "originalPrice": 3.74
    },
    "13010": {
      "code": "13026",
      "price": 3.5,
      "originalPrice": 3.89
    },
    "13011": {
      "code": "13027",
      "price": 3.28,
      "originalPrice": 3.64
    },
    "13012": {
      "code": "13028",
      "price": 3.46,
      "originalPrice": 3.84
    },
    "13013": {
      "code": "13029",
      "price": 3.64,
      "originalPrice": 4.04
    },
    "13014": {
      "code": "13030",
      "price": 3.77,
      "originalPrice": 4.19
    },
    "13015": {
      "code": "13031",
      "price": 3.59,
      "originalPrice": 3.99
    },
    "13016": {
      "code": "13032",
      "price": 3.77,
      "originalPrice": 4.19
    },
    "13017": {
      "code": "13033",
      "price": 3.95,
      "originalPrice": 4.39
    },
    "13018": {
      "code": "13034",
      "price": 4.09,
      "originalPrice": 4.54
    },
    "13035": {
      "code": "13066",
      "price": 1.45,
      "originalPrice": 1.61
    },
    "13036": {
      "code": "13067",
      "price": 1.47,
      "originalPrice": 1.63
    },
    "13037": {
      "code": "13068",
      "price": 1.5,
      "originalPrice": 1.67
    },
    "13038": {
      "code": "13069",
      "price": 1.58,
      "originalPrice": 1.75
    },
    "13039": {
      "code": "13070",
      "price": 1.66,
      "originalPrice": 1.84
    },
    "13040": {
      "code": "13071",
      "price": 1.73,
      "originalPrice": 1.92
    },
    "13041": {
      "code": "13072",
      "price": 1.78,
      "originalPrice": 1.98
    },
    "13042": {
      "code": "13073",
      "price": 1.77,
      "originalPrice": 1.97
    },
    "13043": {
      "code": "13074",
      "price": 1.88,
      "originalPrice": 2.09
    },
    "13044": {
      "code": "13075",
      "price": 1.98,
      "originalPrice": 2.2
    },
    "13045": {
      "code": "13076",
      "price": 2.06,
      "originalPrice": 2.29
    },
    "13046": {
      "code": "13077",
      "price": 1.86,
      "originalPrice": 2.07
    },
    "13047": {
      "code": "13078",
      "price": 1.97,
      "originalPrice": 2.19
    },
    "13048": {
      "code": "13079",
      "price": 2.07,
      "originalPrice": 2.3
    },
    "13049": {
      "code": "13080",
      "price": 2.15,
      "originalPrice": 2.39
    },
    "13050": {
      "code": "13081",
      "price": 1.94,
      "originalPrice": 2.16
    },
    "13051": {
      "code": "13082",
      "price": 2.06,
      "originalPrice": 2.29
    },
    "13052": {
      "code": "13083",
      "price": 2.16,
      "originalPrice": 2.4
    },
    "13053": {
      "code": "13084",
      "price": 2.24,
      "originalPrice": 2.49
    },
    "13054": {
      "code": "13085",
      "price": 2.03,
      "originalPrice": 2.26
    },
    "13055": {
      "code": "13086",
      "price": 2.15,
      "originalPrice": 2.39
    },
    "13056": {
      "code": "13087",
      "price": 2.25,
      "originalPrice": 2.5
    },
    "13057": {
      "code": "13088",
      "price": 2.33,
      "originalPrice": 2.59
    },
    "13058": {
      "code": "13089",
      "price": 2.12,
      "originalPrice": 2.35
    },
    "13059": {
      "code": "13090",
      "price": 2.23,
      "originalPrice": 2.48
    },
    "13060": {
      "code": "13091",
      "price": 2.34,
      "originalPrice": 2.6
    },
    "13061": {
      "code": "13092",
      "price": 2.43,
      "originalPrice": 2.7
    },
    "13062": {
      "code": "13093",
      "price": 2.16,
      "originalPrice": 2.4
    },
    "13063": {
      "code": "13094",
      "price": 2.27,
      "originalPrice": 2.52
    },
    "13064": {
      "code": "13095",
      "price": 2.38,
      "originalPrice": 2.64
    },
    "13065": {
      "code": "13096",
      "price": 2.47,
      "originalPrice": 2.74
    },
    "13097": {
      "code": "13109",
      "price": 3.48,
      "originalPrice": 3.87
    },
    "13098": {
      "code": "13110",
      "price": 3.81,
      "originalPrice": 4.23
    },
    "13099": {
      "code": "13111",
      "price": 4.14,
      "originalPrice": 4.6
    },
    "13100": {
      "code": "13112",
      "price": 3.71,
      "originalPrice": 4.12
    },
    "13101": {
      "code": "13113",
      "price": 4.03,
      "originalPrice": 4.48
    },
    "13102": {
      "code": "13114",
      "price": 4.37,
      "originalPrice": 4.86
    },
    "13103": {
      "code": "13115",
      "price": 3.92,
      "originalPrice": 4.36
    },
    "13104": {
      "code": "13116",
      "price": 4.26,
      "originalPrice": 4.73
    },
    "13105": {
      "code": "13117",
      "price": 4.59,
      "originalPrice": 5.1
    },
    "13106": {
      "code": "13118",
      "price": 4.12,
      "originalPrice": 4.58
    },
    "13107": {
      "code": "13119",
      "price": 4.45,
      "originalPrice": 4.94
    },
    "13108": {
      "code": "13120",
      "price": 4.79,
      "originalPrice": 5.32
    },
    "13121": {
      "code": "13137",
      "price": 2.71,
      "originalPrice": 3.01
    },
    "13122": {
      "code": "13138",
      "price": 2.83,
      "originalPrice": 3.14
    },
    "13123": {
      "code": "13139",
      "price": 2.94,
      "originalPrice": 3.27
    },
    "13124": {
      "code": "13140",
      "price": 3.04,
      "originalPrice": 3.38
    },
    "13125": {
      "code": "13141",
      "price": 3.01,
      "originalPrice": 3.34
    },
    "13126": {
      "code": "13142",
      "price": 3.14,
      "originalPrice": 3.49
    },
    "13127": {
      "code": "13143",
      "price": 3.26,
      "originalPrice": 3.62
    },
    "13128": {
      "code": "13144",
      "price": 3.4,
      "originalPrice": 3.78
    },
    "13129": {
      "code": "13145",
      "price": 3.28,
      "originalPrice": 3.64
    },
    "13130": {
      "code": "13146",
      "price": 3.46,
      "originalPrice": 3.84
    },
    "13131": {
      "code": "13147",
      "price": 3.57,
      "originalPrice": 3.97
    },
    "13132": {
      "code": "13148",
      "price": 3.76,
      "originalPrice": 4.18
    },
    "13133": {
      "code": "13149",
      "price": 3.59,
      "originalPrice": 3.99
    },
    "13134": {
      "code": "13150",
      "price": 3.77,
      "originalPrice": 4.19
    },
    "13135": {
      "code": "13151",
      "price": 3.89,
      "originalPrice": 4.32
    },
    "13136": {
      "code": "13152",
      "price": 4.09,
      "originalPrice": 4.54
    },
    "13153": {
      "code": "13166",
      "price": 2.49,
      "originalPrice": 2.77
    },
    "13154": {
      "code": "13167",
      "price": 2.8,
      "originalPrice": 3.11
    },
    "13155": {
      "code": "13168",
      "price": 3.1,
      "originalPrice": 3.44
    },
    "13156": {
      "code": "13169",
      "price": 3.59,
      "originalPrice": 3.99
    },
    "13157": {
      "code": "13170",
      "price": 3.92,
      "originalPrice": 4.35
    },
    "13158": {
      "code": "13171",
      "price": 2.81,
      "originalPrice": 3.12
    },
    "13159": {
      "code": "13172",
      "price": 3.15,
      "originalPrice": 3.5
    },
    "13160": {
      "code": "13173",
      "price": 3.02,
      "originalPrice": 3.36
    },
    "13161": {
      "code": "13174",
      "price": 3.38,
      "originalPrice": 3.75
    },
    "13162": {
      "code": "13175",
      "price": 3.24,
      "originalPrice": 3.6
    },
    "13163": {
      "code": "13176",
      "price": 3.59,
      "originalPrice": 3.99
    },
    "13164": {
      "code": "13177",
      "price": 3.43,
      "originalPrice": 3.81
    },
    "13165": {
      "code": "13178",
      "price": 3.78,
      "originalPrice": 4.2
    },
    "13179": {
      "code": "13209",
      "price": 1.34,
      "originalPrice": 1.49
    },
    "13180": {
      "code": "13210",
      "price": 1.38,
      "originalPrice": 1.53
    },
    "13181": {
      "code": "13211",
      "price": 1.43,
      "originalPrice": 1.59
    },
    "13182": {
      "code": "13212",
      "price": 1.49,
      "originalPrice": 1.66
    },
    "13183": {
      "code": "13213",
      "price": 1.55,
      "originalPrice": 1.72
    },
    "13184": {
      "code": "13214",
      "price": 1.58,
      "originalPrice": 1.76
    },
    "13185": {
      "code": "13215",
      "price": 1.64,
      "originalPrice": 1.82
    },
    "13186": {
      "code": "13216",
      "price": 1.73,
      "originalPrice": 1.92
    },
    "13187": {
      "code": "13217",
      "price": 1.82,
      "originalPrice": 2.02
    },
    "13188": {
      "code": "13218",
      "price": 1.87,
      "originalPrice": 2.08
    },
    "13189": {
      "code": "13219",
      "price": 1.71,
      "originalPrice": 1.9
    },
    "13190": {
      "code": "13220",
      "price": 1.81,
      "originalPrice": 2.01
    },
    "13191": {
      "code": "13221",
      "price": 1.9,
      "originalPrice": 2.11
    },
    "13192": {
      "code": "13222",
      "price": 1.96,
      "originalPrice": 2.18
    },
    "13193": {
      "code": "13223",
      "price": 1.79,
      "originalPrice": 1.99
    },
    "13194": {
      "code": "13224",
      "price": 1.89,
      "originalPrice": 2.1
    },
    "13195": {
      "code": "13225",
      "price": 1.98,
      "originalPrice": 2.2
    },
    "13196": {
      "code": "13226",
      "price": 2.04,
      "originalPrice": 2.27
    },
    "13197": {
      "code": "13227",
      "price": 1.86,
      "originalPrice": 2.07
    },
    "13198": {
      "code": "13228",
      "price": 1.96,
      "originalPrice": 2.18
    },
    "13199": {
      "code": "13229",
      "price": 2.06,
      "originalPrice": 2.29
    },
    "13200": {
      "code": "13230",
      "price": 2.12,
      "originalPrice": 2.36
    },
    "13201": {
      "code": "13231",
      "price": 1.96,
      "originalPrice": 2.18
    },
    "13202": {
      "code": "13232",
      "price": 2.07,
      "originalPrice": 2.3
    },
    "13203": {
      "code": "13233",
      "price": 2.17,
      "originalPrice": 2.41
    },
    "13204": {
      "code": "13234",
      "price": 2.23,
      "originalPrice": 2.48
    },
    "13205": {
      "code": "13235",
      "price": 2,
      "originalPrice": 2.22
    },
    "13206": {
      "code": "13236",
      "price": 2.1,
      "originalPrice": 2.33
    },
    "13207": {
      "code": "13237",
      "price": 2.2,
      "originalPrice": 2.44
    },
    "13208": {
      "code": "13238",
      "price": 2.27,
      "originalPrice": 2.52
    },
    "13239": {
      "code": "13255",
      "price": 2.57,
      "originalPrice": 2.86
    },
    "13240": {
      "code": "13256",
      "price": 2.65,
      "originalPrice": 2.94
    },
    "13241": {
      "code": "13257",
      "price": 2.76,
      "originalPrice": 3.07
    },
    "13242": {
      "code": "13258",
      "price": 2.86,
      "originalPrice": 3.18
    },
    "13243": {
      "code": "13259",
      "price": 2.93,
      "originalPrice": 3.26
    },
    "13244": {
      "code": "13260",
      "price": 3.01,
      "originalPrice": 3.34
    },
    "13245": {
      "code": "13261",
      "price": 3.12,
      "originalPrice": 3.47
    },
    "13246": {
      "code": "13262",
      "price": 3.27,
      "originalPrice": 3.63
    },
    "13247": {
      "code": "13263",
      "price": 3.34,
      "originalPrice": 3.71
    },
    "13248": {
      "code": "13264",
      "price": 3.41,
      "originalPrice": 3.79
    },
    "13249": {
      "code": "13265",
      "price": 3.53,
      "originalPrice": 3.92
    },
    "13250": {
      "code": "13266",
      "price": 3.72,
      "originalPrice": 4.13
    },
    "13251": {
      "code": "13267",
      "price": 3.79,
      "originalPrice": 4.21
    },
    "13252": {
      "code": "13268",
      "price": 3.86,
      "originalPrice": 4.29
    },
    "13253": {
      "code": "13269",
      "price": 3.98,
      "originalPrice": 4.42
    },
    "13254": {
      "code": "13270",
      "price": 4.21,
      "originalPrice": 4.68
    },
    "13271": {
      "code": "13301",
      "price": 1.39,
      "originalPrice": 1.54
    },
    "13272": {
      "code": "13302",
      "price": 1.4,
      "originalPrice": 1.56
    },
    "13273": {
      "code": "13303",
      "price": 1.45,
      "originalPrice": 1.61
    },
    "13274": {
      "code": "13304",
      "price": 1.49,
      "originalPrice": 1.66
    },
    "13275": {
      "code": "13305",
      "price": 1.53,
      "originalPrice": 1.7
    },
    "13276": {
      "code": "13306",
      "price": 1.8,
      "originalPrice": 2
    },
    "13277": {
      "code": "13307",
      "price": 1.67,
      "originalPrice": 1.85
    },
    "13278": {
      "code": "13308",
      "price": 1.75,
      "originalPrice": 1.94
    },
    "13279": {
      "code": "13309",
      "price": 1.83,
      "originalPrice": 2.03
    },
    "13280": {
      "code": "13310",
      "price": 1.89,
      "originalPrice": 2.1
    },
    "13281": {
      "code": "13311",
      "price": 1.74,
      "originalPrice": 1.93
    },
    "13282": {
      "code": "13312",
      "price": 1.82,
      "originalPrice": 2.02
    },
    "13283": {
      "code": "13313",
      "price": 1.9,
      "originalPrice": 2.11
    },
    "13284": {
      "code": "13314",
      "price": 1.97,
      "originalPrice": 2.19
    },
    "13285": {
      "code": "13315",
      "price": 1.81,
      "originalPrice": 2.01
    },
    "13286": {
      "code": "13316",
      "price": 1.9,
      "originalPrice": 2.11
    },
    "13287": {
      "code": "13317",
      "price": 1.99,
      "originalPrice": 2.21
    },
    "13288": {
      "code": "13318",
      "price": 2.05,
      "originalPrice": 2.28
    },
    "13289": {
      "code": "13319",
      "price": 1.89,
      "originalPrice": 2.1
    },
    "13290": {
      "code": "13320",
      "price": 1.98,
      "originalPrice": 2.2
    },
    "13291": {
      "code": "13321",
      "price": 2.07,
      "originalPrice": 2.3
    },
    "13292": {
      "code": "13322",
      "price": 2.14,
      "originalPrice": 2.38
    },
    "13293": {
      "code": "13323",
      "price": 1.99,
      "originalPrice": 2.21
    },
    "13294": {
      "code": "13324",
      "price": 2.09,
      "originalPrice": 2.32
    },
    "13295": {
      "code": "13325",
      "price": 2.18,
      "originalPrice": 2.42
    },
    "13296": {
      "code": "13326",
      "price": 2.26,
      "originalPrice": 2.51
    },
    "13297": {
      "code": "13327",
      "price": 2.03,
      "originalPrice": 2.25
    },
    "13298": {
      "code": "13328",
      "price": 2.12,
      "originalPrice": 2.36
    },
    "13299": {
      "code": "13329",
      "price": 2.21,
      "originalPrice": 2.45
    },
    "13300": {
      "code": "13330",
      "price": 2.29,
      "originalPrice": 2.54
    },
    "13334": {
      "code": "13363",
      "price": 1.64,
      "originalPrice": 1.82
    },
    "13335": {
      "code": "13364",
      "price": 1.7,
      "originalPrice": 1.89
    },
    "13336": {
      "code": "13365",
      "price": 1.76,
      "originalPrice": 1.95
    },
    "13337": {
      "code": "13366",
      "price": 1.81,
      "originalPrice": 2.01
    },
    "13338": {
      "code": "13367",
      "price": 1.85,
      "originalPrice": 2.05
    },
    "13339": {
      "code": "13368",
      "price": 1.75,
      "originalPrice": 1.94
    },
    "13340": {
      "code": "13369",
      "price": 1.8,
      "originalPrice": 2
    },
    "13341": {
      "code": "13370",
      "price": 1.85,
      "originalPrice": 2.06
    },
    "13342": {
      "code": "13371",
      "price": 1.89,
      "originalPrice": 2.1
    },
    "13343": {
      "code": "13372",
      "price": 1.78,
      "originalPrice": 1.98
    },
    "13344": {
      "code": "13373",
      "price": 1.84,
      "originalPrice": 2.04
    },
    "13345": {
      "code": "13374",
      "price": 1.89,
      "originalPrice": 2.1
    },
    "13346": {
      "code": "13375",
      "price": 1.94,
      "originalPrice": 2.15
    },
    "13347": {
      "code": "13376",
      "price": 1.83,
      "originalPrice": 2.03
    },
    "13348": {
      "code": "13377",
      "price": 1.88,
      "originalPrice": 2.09
    },
    "13349": {
      "code": "13378",
      "price": 1.94,
      "originalPrice": 2.15
    },
    "13350": {
      "code": "13379",
      "price": 1.98,
      "originalPrice": 2.2
    },
    "13351": {
      "code": "13380",
      "price": 1.87,
      "originalPrice": 2.08
    },
    "13352": {
      "code": "13381",
      "price": 1.93,
      "originalPrice": 2.14
    },
    "13353": {
      "code": "13382",
      "price": 1.98,
      "originalPrice": 2.2
    },
    "13354": {
      "code": "13383",
      "price": 2.03,
      "originalPrice": 2.25
    },
    "13355": {
      "code": "13384",
      "price": 1.92,
      "originalPrice": 2.13
    },
    "13356": {
      "code": "13385",
      "price": 1.97,
      "originalPrice": 2.19
    },
    "13357": {
      "code": "13386",
      "price": 2.03,
      "originalPrice": 2.25
    },
    "13358": {
      "code": "13387",
      "price": 2.06,
      "originalPrice": 2.29
    },
    "13359": {
      "code": "13388",
      "price": 1.95,
      "originalPrice": 2.17
    },
    "13360": {
      "code": "13389",
      "price": 2.01,
      "originalPrice": 2.23
    },
    "13361": {
      "code": "13390",
      "price": 2.06,
      "originalPrice": 2.29
    },
    "13362": {
      "code": "13391",
      "price": 2.11,
      "originalPrice": 2.34
    },
    "13393": {
      "code": "13420",
      "price": 0.95,
      "originalPrice": 1.06
    },
    "13394": {
      "code": "13421",
      "price": 0.98,
      "originalPrice": 1.09
    },
    "13395": {
      "code": "13422",
      "price": 1.02,
      "originalPrice": 1.13
    },
    "13396": {
      "code": "13423",
      "price": 1.05,
      "originalPrice": 1.17
    },
    "13397": {
      "code": "13424",
      "price": 1.08,
      "originalPrice": 1.2
    },
    "13398": {
      "code": "13425",
      "price": 1.04,
      "originalPrice": 1.15
    },
    "13399": {
      "code": "13426",
      "price": 1.07,
      "originalPrice": 1.19
    },
    "13400": {
      "code": "13427",
      "price": 1.1,
      "originalPrice": 1.22
    },
    "13401": {
      "code": "13428",
      "price": 1.13,
      "originalPrice": 1.25
    },
    "13402": {
      "code": "13429",
      "price": 1.08,
      "originalPrice": 1.2
    },
    "13403": {
      "code": "13430",
      "price": 1.12,
      "originalPrice": 1.24
    },
    "13404": {
      "code": "13431",
      "price": 1.15,
      "originalPrice": 1.28
    },
    "13405": {
      "code": "13432",
      "price": 1.18,
      "originalPrice": 1.31
    },
    "13406": {
      "code": "13433",
      "price": 1.13,
      "originalPrice": 1.26
    },
    "13407": {
      "code": "13434",
      "price": 1.16,
      "originalPrice": 1.29
    },
    "13408": {
      "code": "13435",
      "price": 1.2,
      "originalPrice": 1.33
    },
    "13409": {
      "code": "13436",
      "price": 1.22,
      "originalPrice": 1.36
    },
    "13410": {
      "code": "13437",
      "price": 1.22,
      "originalPrice": 1.35
    },
    "13411": {
      "code": "13438",
      "price": 1.24,
      "originalPrice": 1.38
    },
    "13412": {
      "code": "13439",
      "price": 1.28,
      "originalPrice": 1.42
    },
    "13413": {
      "code": "13440",
      "price": 1.26,
      "originalPrice": 1.4
    },
    "13414": {
      "code": "13441",
      "price": 1.29,
      "originalPrice": 1.43
    },
    "13415": {
      "code": "13442",
      "price": 1.32,
      "originalPrice": 1.47
    },
    "13416": {
      "code": "13443",
      "price": 1.25,
      "originalPrice": 1.39
    },
    "13417": {
      "code": "13444",
      "price": 1.29,
      "originalPrice": 1.43
    },
    "13418": {
      "code": "13445",
      "price": 1.32,
      "originalPrice": 1.47
    },
    "13419": {
      "code": "13446",
      "price": 1.35,
      "originalPrice": 1.5
    },
    "13447": {
      "code": "13476",
      "price": 1.09,
      "originalPrice": 1.21
    },
    "13448": {
      "code": "13477",
      "price": 1.13,
      "originalPrice": 1.25
    },
    "13449": {
      "code": "13478",
      "price": 1.12,
      "originalPrice": 1.24
    },
    "13450": {
      "code": "13479",
      "price": 1.14,
      "originalPrice": 1.27
    },
    "13451": {
      "code": "13480",
      "price": 1.13,
      "originalPrice": 1.26
    },
    "13452": {
      "code": "13481",
      "price": 1.2,
      "originalPrice": 1.33
    },
    "13453": {
      "code": "13482",
      "price": 1.28,
      "originalPrice": 1.42
    },
    "13454": {
      "code": "13483",
      "price": 1.33,
      "originalPrice": 1.48
    },
    "13455": {
      "code": "13484",
      "price": 1.4,
      "originalPrice": 1.55
    },
    "13456": {
      "code": "13485",
      "price": 1.26,
      "originalPrice": 1.4
    },
    "13457": {
      "code": "13486",
      "price": 1.32,
      "originalPrice": 1.47
    },
    "13458": {
      "code": "13487",
      "price": 1.4,
      "originalPrice": 1.56
    },
    "13459": {
      "code": "13488",
      "price": 1.5,
      "originalPrice": 1.67
    },
    "13460": {
      "code": "13489",
      "price": 1.33,
      "originalPrice": 1.48
    },
    "13461": {
      "code": "13490",
      "price": 1.37,
      "originalPrice": 1.52
    },
    "13462": {
      "code": "13491",
      "price": 1.42,
      "originalPrice": 1.58
    },
    "13463": {
      "code": "13492",
      "price": 1.56,
      "originalPrice": 1.73
    },
    "13464": {
      "code": "13493",
      "price": 1.46,
      "originalPrice": 1.62
    },
    "13465": {
      "code": "13494",
      "price": 1.51,
      "originalPrice": 1.68
    },
    "13466": {
      "code": "13495",
      "price": 1.57,
      "originalPrice": 1.74
    },
    "13467": {
      "code": "13496",
      "price": 1.64,
      "originalPrice": 1.82
    },
    "13468": {
      "code": "13497",
      "price": 1.6,
      "originalPrice": 1.78
    },
    "13469": {
      "code": "13498",
      "price": 1.67,
      "originalPrice": 1.86
    },
    "13470": {
      "code": "13499",
      "price": 1.88,
      "originalPrice": 2.09
    },
    "13471": {
      "code": "13500",
      "price": 1.93,
      "originalPrice": 2.14
    },
    "13472": {
      "code": "13501",
      "price": 1.88,
      "originalPrice": 2.09
    },
    "13473": {
      "code": "13502",
      "price": 1.95,
      "originalPrice": 2.17
    },
    "13474": {
      "code": "13503",
      "price": 2.03,
      "originalPrice": 2.26
    },
    "13475": {
      "code": "13504",
      "price": 2.14,
      "originalPrice": 2.38
    },
    "13505": {
      "code": "13533",
      "price": 1.87,
      "originalPrice": 2.08
    },
    "13506": {
      "code": "13534",
      "price": 1.98,
      "originalPrice": 2.2
    },
    "13507": {
      "code": "13535",
      "price": 1.96,
      "originalPrice": 2.18
    },
    "13508": {
      "code": "13536",
      "price": 2.05,
      "originalPrice": 2.28
    },
    "13509": {
      "code": "13537",
      "price": 2.27,
      "originalPrice": 2.52
    },
    "13510": {
      "code": "13538",
      "price": 2.73,
      "originalPrice": 3.03
    },
    "13511": {
      "code": "13539",
      "price": 2.97,
      "originalPrice": 3.3
    },
    "13512": {
      "code": "13540",
      "price": 2.46,
      "originalPrice": 2.73
    },
    "13513": {
      "code": "13541",
      "price": 2.75,
      "originalPrice": 3.05
    },
    "13514": {
      "code": "13542",
      "price": 3.21,
      "originalPrice": 3.57
    },
    "13515": {
      "code": "13543",
      "price": 2.7,
      "originalPrice": 3
    },
    "13516": {
      "code": "13544",
      "price": 2.94,
      "originalPrice": 3.27
    },
    "13517": {
      "code": "13545",
      "price": 3.16,
      "originalPrice": 3.51
    },
    "13518": {
      "code": "13546",
      "price": 3.41,
      "originalPrice": 3.79
    },
    "13519": {
      "code": "13547",
      "price": 2.9,
      "originalPrice": 3.22
    },
    "13520": {
      "code": "13548",
      "price": 3.15,
      "originalPrice": 3.5
    },
    "13521": {
      "code": "13549",
      "price": 3.37,
      "originalPrice": 3.74
    },
    "13522": {
      "code": "13550",
      "price": 3.62,
      "originalPrice": 4.02
    },
    "13523": {
      "code": "13551",
      "price": 3.08,
      "originalPrice": 3.42
    },
    "13524": {
      "code": "13552",
      "price": 3.32,
      "originalPrice": 3.69
    },
    "13525": {
      "code": "13553",
      "price": 3.54,
      "originalPrice": 3.93
    },
    "13526": {
      "code": "13554",
      "price": 3.79,
      "originalPrice": 4.21
    },
    "13527": {
      "code": "13555",
      "price": 3.27,
      "originalPrice": 3.63
    },
    "13528": {
      "code": "13556",
      "price": 3.51,
      "originalPrice": 3.9
    },
    "13529": {
      "code": "13557",
      "price": 3.73,
      "originalPrice": 4.14
    },
    "13530": {
      "code": "13558",
      "price": 3.74,
      "originalPrice": 4.15
    },
    "13531": {
      "code": "13559",
      "price": 3.75,
      "originalPrice": 4.16
    },
    "13532": {
      "code": "13560",
      "price": 3.98,
      "originalPrice": 4.42
    }
  },
  "consalud": {
    "13-SF17-26": {
      "code": "63-SF17-26",
      "price": 3.19,
      "originalPrice": 3.36
    },
    "13-SF27-26": {
      "code": "63-SF27-26",
      "price": 3.4,
      "originalPrice": 3.58
    },
    "13-SF37-26": {
      "code": "63-SF37-26",
      "price": 3.54,
      "originalPrice": 3.73
    },
    "13-SF47-26": {
      "code": "63-SF47-26",
      "price": 3.47,
      "originalPrice": 3.65
    },
    "13-SF57-26": {
      "code": "63-SF57-26",
      "price": 3.72,
      "originalPrice": 3.92
    },
    "13-SF67-26": {
      "code": "63-SF67-26",
      "price": 3.86,
      "originalPrice": 4.06
    },
    "13-SF77-26": {
      "code": "63-SF77-26",
      "price": 3.56,
      "originalPrice": 3.75
    },
    "13-SF87-26": {
      "code": "63-SF87-26",
      "price": 3.97,
      "originalPrice": 4.18
    },
    "13-SF97-26": {
      "code": "63-SF97-26",
      "price": 4.1,
      "originalPrice": 4.32
    },
    "13-SF107-26": {
      "code": "63-SF107-26",
      "price": 3.85,
      "originalPrice": 4.05
    },
    "13-SF117-26": {
      "code": "63-SF117-26",
      "price": 3.86,
      "originalPrice": 4.06
    },
    "13-SF127-26": {
      "code": "63-SF127-26",
      "price": 4.07,
      "originalPrice": 4.28
    },
    "13-SF137-26": {
      "code": "63-SF137-26",
      "price": 4.19,
      "originalPrice": 4.41
    },
    "13-SF147-26": {
      "code": "63-SF147-26",
      "price": 4.6,
      "originalPrice": 4.84
    },
    "13-SF157-26": {
      "code": "63-SF157-26",
      "price": 3.94,
      "originalPrice": 4.15
    },
    "13-SF167-26": {
      "code": "63-SF167-26",
      "price": 4.28,
      "originalPrice": 4.51
    },
    "13-SF177-26": {
      "code": "63-SF177-26",
      "price": 4.75,
      "originalPrice": 5
    },
    "13-SF187-26": {
      "code": "63-SF187-26",
      "price": 4.31,
      "originalPrice": 4.54
    },
    "13-SF197-26": {
      "code": "63-SF197-26",
      "price": 4.62,
      "originalPrice": 4.86
    },
    "13-SF207-26": {
      "code": "63-SF207-26",
      "price": 4.96,
      "originalPrice": 5.22
    },
    "13-SF217-26": {
      "code": "63-SF217-26",
      "price": 4.88,
      "originalPrice": 5.14
    },
    "13-SF227-26": {
      "code": "63-SF227-26",
      "price": 5.05,
      "originalPrice": 5.32
    },
    "13-SF237-26": {
      "code": "63-SF237-26",
      "price": 5.81,
      "originalPrice": 6.12
    },
    "13-SF247-26": {
      "code": "63-SF247-26",
      "price": 5.84,
      "originalPrice": 6.15
    },
    "13-SF257-26": {
      "code": "63-SF257-26",
      "price": 5.92,
      "originalPrice": 6.23
    },
    "13-SF267-26": {
      "code": "63-SF267-26",
      "price": 6.04,
      "originalPrice": 6.36
    },
    "13-FCS17-26": {
      "code": "63-FCS17-26",
      "price": 2.32,
      "originalPrice": 2.43
    },
    "13-FCS27-26": {
      "code": "63-FCS27-26",
      "price": 2.48,
      "originalPrice": 2.6
    },
    "13-FCS37-26": {
      "code": "63-FCS37-26",
      "price": 2.86,
      "originalPrice": 3
    },
    "13-FCS47-26": {
      "code": "63-FCS47-26",
      "price": 2.62,
      "originalPrice": 2.75
    },
    "13-FCS57-26": {
      "code": "63-FCS57-26",
      "price": 2.75,
      "originalPrice": 2.88
    },
    "13-FCS67-26": {
      "code": "63-FCS67-26",
      "price": 3.09,
      "originalPrice": 3.24
    },
    "13-FCS057-26": {
      "code": "63-FCS057-26",
      "price": 2.15,
      "originalPrice": 2.26
    },
    "13-FCS657-26": {
      "code": "63-FCS657-26",
      "price": 2.85,
      "originalPrice": 3
    },
    "13-FCS857-26": {
      "code": "63-FCS857-26",
      "price": 3.14,
      "originalPrice": 3.3
    },
    "13-FCS957-26": {
      "code": "63-FCS957-26",
      "price": 3.12,
      "originalPrice": 3.28
    },
    "13-FCS1057-26": {
      "code": "63-FCS1057-26",
      "price": 3.35,
      "originalPrice": 3.53
    },
    "13-FCS1557-26": {
      "code": "63-FCS1557-26",
      "price": 3.72,
      "originalPrice": 3.92
    },
    "13-FCS1307-26": {
      "code": "63-FCS1307-26",
      "price": 3.45,
      "originalPrice": 3.63
    },
    "13-FCS1407-26": {
      "code": "63-FCS1407-26",
      "price": 3.47,
      "originalPrice": 3.65
    },
    "13-SO1002-26": {
      "code": "63-SO1003-26",
      "price": 2.67,
      "originalPrice": 2.81
    },
    "13-SO2002-26": {
      "code": "63-SO2003-26",
      "price": 2.77,
      "originalPrice": 2.92
    },
    "13-SO3002-26": {
      "code": "63-SO3003-26",
      "price": 2.95,
      "originalPrice": 3.1
    },
    "13-SO4002-26": {
      "code": "63-SO4003-26",
      "price": 2.96,
      "originalPrice": 3.12
    },
    "13-SO5002-26": {
      "code": "63-SO5003-26",
      "price": 3.13,
      "originalPrice": 3.29
    },
    "13-LF1001-26": {
      "code": "63-LF1003-26",
      "price": 2.17,
      "originalPrice": 2.28
    },
    "13-LF2001-26": {
      "code": "63-LF2003-26",
      "price": 2.27,
      "originalPrice": 2.39
    },
    "13-LF3001-26": {
      "code": "63-LF3003-26",
      "price": 2.4,
      "originalPrice": 2.53
    },
    "13-LF4001-26": {
      "code": "63-LF4003-26",
      "price": 2.34,
      "originalPrice": 2.46
    },
    "13-LF5001-26": {
      "code": "63-LF5003-26",
      "price": 2.3,
      "originalPrice": 2.42
    },
    "13-LF6001-26": {
      "code": "63-LF6003-26",
      "price": 2.43,
      "originalPrice": 2.56
    },
    "13-LF7001-26": {
      "code": "63-LF7003-26",
      "price": 2.21,
      "originalPrice": 2.33
    },
    "13-LF8001-26": {
      "code": "63-LF8003-26",
      "price": 2.34,
      "originalPrice": 2.46
    },
    "13-LF9001-26": {
      "code": "63-LF9003-26",
      "price": 2.63,
      "originalPrice": 2.77
    },
    "13-LF107-26": {
      "code": "63-LF107-26",
      "price": 2.35,
      "originalPrice": 2.47
    },
    "13-LF117-26": {
      "code": "63-LF117-26",
      "price": 2.52,
      "originalPrice": 2.65
    },
    "13-LF127-26": {
      "code": "63-LF127-26",
      "price": 2.48,
      "originalPrice": 2.61
    },
    "13-LF137-26": {
      "code": "63-LF137-26",
      "price": 2.63,
      "originalPrice": 2.77
    },
    "13-LF147-26": {
      "code": "63-LF147-26",
      "price": 2.66,
      "originalPrice": 2.8
    },
    "13-LF157-26": {
      "code": "63-LF157-26",
      "price": 2.83,
      "originalPrice": 2.98
    },
    "13-LF167-26": {
      "code": "63-LF167-26",
      "price": 2.67,
      "originalPrice": 2.81
    },
    "13-LF177-26": {
      "code": "63-LF177-26",
      "price": 2.86,
      "originalPrice": 3.01
    },
    "13-LF187-26": {
      "code": "63-LF187-26",
      "price": 2.95,
      "originalPrice": 3.1
    },
    "13-LF197-26": {
      "code": "63-LF197-26",
      "price": 2.71,
      "originalPrice": 2.85
    },
    "13-LF207-26": {
      "code": "63-LF207-26",
      "price": 2.91,
      "originalPrice": 3.06
    },
    "13-LF217-26": {
      "code": "63-LF217-26",
      "price": 2.99,
      "originalPrice": 3.15
    },
    "13-LF227-26": {
      "code": "63-LF227-26",
      "price": 2.74,
      "originalPrice": 2.88
    },
    "13-LF237-26": {
      "code": "63-LF237-26",
      "price": 2.86,
      "originalPrice": 3.01
    },
    "13-LF247-26": {
      "code": "63-LF247-26",
      "price": 2.94,
      "originalPrice": 3.09
    },
    "13-LF257-26": {
      "code": "63-LF257-26",
      "price": 3,
      "originalPrice": 3.16
    },
    "13-LF267-26": {
      "code": "63-LF267-26",
      "price": 2.82,
      "originalPrice": 2.97
    },
    "13-LF277-26": {
      "code": "63-LF277-26",
      "price": 2.95,
      "originalPrice": 3.1
    },
    "13-LF287-26": {
      "code": "63-LF287-26",
      "price": 3.14,
      "originalPrice": 3.3
    },
    "13-LF297-26": {
      "code": "63-LF297-26",
      "price": 2.83,
      "originalPrice": 2.98
    },
    "13-LF307-26": {
      "code": "63-LF307-26",
      "price": 2.98,
      "originalPrice": 3.14
    },
    "13-LF317-26": {
      "code": "63-LF317-26",
      "price": 3.17,
      "originalPrice": 3.34
    },
    "13-FCL10-26": {
      "code": "63-FCL10-26",
      "price": 1.42,
      "originalPrice": 1.49
    },
    "13-FCL20-26": {
      "code": "63-FCL20-26",
      "price": 1.57,
      "originalPrice": 1.65
    },
    "13-FCL30-26": {
      "code": "63-FCL30-26",
      "price": 1.75,
      "originalPrice": 1.84
    },
    "13-FCL40-26": {
      "code": "63-FCL40-26",
      "price": 1.53,
      "originalPrice": 1.61
    },
    "13-FCL50-26": {
      "code": "63-FCL50-26",
      "price": 1.86,
      "originalPrice": 1.96
    },
    "13-FCL60-26": {
      "code": "63-FCL60-26",
      "price": 1.82,
      "originalPrice": 1.92
    },
    "13-FCL70-26": {
      "code": "63-FCL70-26",
      "price": 1.89,
      "originalPrice": 1.99
    },
    "13-FCL80-26": {
      "code": "63-FCL80-26",
      "price": 2.07,
      "originalPrice": 2.18
    },
    "13-FCL904-26": {
      "code": "63-FCL904-26",
      "price": 2.27,
      "originalPrice": 2.39
    },
    "13-FCL100-26": {
      "code": "63-FCL100-26",
      "price": 2.32,
      "originalPrice": 2.44
    },
    "13-FCL110-26": {
      "code": "63-FCL110-26",
      "price": 2.11,
      "originalPrice": 2.22
    },
    "13-FCL120-26": {
      "code": "63-FCL120-26",
      "price": 2.31,
      "originalPrice": 2.43
    },
    "13-FCL130-26": {
      "code": "63-FCL130-26",
      "price": 2.47,
      "originalPrice": 2.6
    },
    "13-FCL140-26": {
      "code": "63-FCL140-26",
      "price": 1.68,
      "originalPrice": 1.77
    },
    "13-FCL150-26": {
      "code": "63-FCL150-26",
      "price": 1.73,
      "originalPrice": 1.82
    },
    "13-FCL160-26": {
      "code": "63-FCL160-26",
      "price": 2.03,
      "originalPrice": 2.14
    },
    "13-FCL177-26": {
      "code": "63-FCL177-26",
      "price": 1.85,
      "originalPrice": 1.94
    },
    "13-FCL187-26": {
      "code": "63-FCL187-26",
      "price": 1.91,
      "originalPrice": 2
    },
    "13-FCL197-26": {
      "code": "63-FCL197-26",
      "price": 2.11,
      "originalPrice": 2.21
    },
    "13-FCL207-26": {
      "code": "63-FCL207-26",
      "price": 2.36,
      "originalPrice": 2.47
    },
    "13-FCL217-26": {
      "code": "63-FCL217-26",
      "price": 2.29,
      "originalPrice": 2.39
    },
    "13-FCL227-26": {
      "code": "63-FCL227-26",
      "price": 2.17,
      "originalPrice": 2.26
    },
    "13-FCL237-26": {
      "code": "63-FCL237-26",
      "price": 2.35,
      "originalPrice": 2.45
    },
    "13-FCL247-26": {
      "code": "63-FCL247-26",
      "price": 2.45,
      "originalPrice": 2.56
    },
    "13-FCL257-26": {
      "code": "63-FCL257-26",
      "price": 2.57,
      "originalPrice": 2.69
    },
    "13-FCL267-26": {
      "code": "63-FCL267-26",
      "price": 2.37,
      "originalPrice": 2.47
    },
    "13-FCL277-26": {
      "code": "63-FCL277-26",
      "price": 2.51,
      "originalPrice": 2.62
    },
    "13-FCL287-26": {
      "code": "63-FCL287-26",
      "price": 2.57,
      "originalPrice": 2.68
    },
    "13-FCL297-26": {
      "code": "63-FCL297-26",
      "price": 2.68,
      "originalPrice": 2.8
    },
    "13-FCL307-26": {
      "code": "63-FCL307-26",
      "price": 2.87,
      "originalPrice": 3
    },
    "13-FCL317-26": {
      "code": "63-FCL317-26",
      "price": 2.91,
      "originalPrice": 3.03
    },
    "13-FCL327-26": {
      "code": "63-FCL327-26",
      "price": 2.96,
      "originalPrice": 3.09
    },
    "13-FCL505-26": {
      "code": "63-FCL505-26",
      "price": 1.77,
      "originalPrice": 1.86
    },
    "13-FCL557-26": {
      "code": "63-FCL557-26",
      "price": 1.61,
      "originalPrice": 1.69
    },
    "13-FCL605-26": {
      "code": "63-FCL605-26",
      "price": 1.88,
      "originalPrice": 1.98
    },
    "13-FCL1157-26": {
      "code": "63-FCL1157-26",
      "price": 2.05,
      "originalPrice": 2.16
    },
    "13-FCL1105-26": {
      "code": "63-FCL1105-26",
      "price": 2.27,
      "originalPrice": 2.39
    },
    "13-FCL1317-26": {
      "code": "63-FCL1317-26",
      "price": 2.03,
      "originalPrice": 2.14
    },
    "13-FCL1327-26": {
      "code": "63-FCL1327-26",
      "price": 2.14,
      "originalPrice": 2.25
    },
    "13-FCL1337-26": {
      "code": "63-FCL1337-26",
      "price": 2.29,
      "originalPrice": 2.41
    },
    "13-FCL1347-26": {
      "code": "63-FCL1347-26",
      "price": 2.34,
      "originalPrice": 2.46
    },
    "13-LO1002-26": {
      "code": "63-LO1003-26",
      "price": 1.84,
      "originalPrice": 1.94
    },
    "13-LO2002-26": {
      "code": "63-LO2003-26",
      "price": 1.86,
      "originalPrice": 1.96
    },
    "13-LO3002-26": {
      "code": "63-LO3003-26",
      "price": 1.94,
      "originalPrice": 2.04
    },
    "13-LO4002-26": {
      "code": "63-LO4003-26",
      "price": 2.03,
      "originalPrice": 2.14
    },
    "13-LO5002-26": {
      "code": "63-LO5003-26",
      "price": 1.93,
      "originalPrice": 2.03
    },
    "13-LO6002-26": {
      "code": "63-LO6003-26",
      "price": 2,
      "originalPrice": 2.11
    },
    "13-LO7002-26": {
      "code": "63-LO7003-26",
      "price": 2.08,
      "originalPrice": 2.19
    },
    "13-LO8002-26": {
      "code": "63-LO8003-26",
      "price": 2.18,
      "originalPrice": 2.29
    },
    "13-LO9002-26": {
      "code": "63-LO9003-26",
      "price": 2.33,
      "originalPrice": 2.45
    },
    "13-LO10002-26": {
      "code": "63-LO10003-26",
      "price": 2.25,
      "originalPrice": 2.37
    },
    "13-LO11002-26": {
      "code": "63-LO11003-26",
      "price": 2.37,
      "originalPrice": 2.49
    },
    "13-LO12002-26": {
      "code": "63-LO12003-26",
      "price": 2.38,
      "originalPrice": 2.51
    },
    "13-LO13002-26": {
      "code": "63-LO13003-26",
      "price": 2.48,
      "originalPrice": 2.61
    },
    "13-EF1001-26": {
      "code": "63-EF1003-26",
      "price": 1.43,
      "originalPrice": 1.5
    },
    "13-EF2001-26": {
      "code": "63-EF2003-26",
      "price": 1.62,
      "originalPrice": 1.7
    },
    "13-EF3001-26": {
      "code": "63-EF3003-26",
      "price": 1.38,
      "originalPrice": 1.45
    },
    "13-EF4001-26": {
      "code": "63-EF4003-26",
      "price": 1.49,
      "originalPrice": 1.57
    },
    "13-EF5001-26": {
      "code": "63-EF5003-26",
      "price": 1.67,
      "originalPrice": 1.76
    },
    "13-EF6001-26": {
      "code": "63-EF6003-26",
      "price": 1.51,
      "originalPrice": 1.59
    },
    "13-EF7001-26": {
      "code": "63-EF7003-26",
      "price": 1.63,
      "originalPrice": 1.72
    },
    "13-EF8001-26": {
      "code": "63-EF8003-26",
      "price": 1.81,
      "originalPrice": 1.9
    },
    "13-EF9001-26": {
      "code": "63-EF9003-26",
      "price": 1.96,
      "originalPrice": 2.06
    },
    "13-EF10001-26": {
      "code": "63-EF10003-26",
      "price": 1.66,
      "originalPrice": 1.75
    },
    "13-EF11001-26": {
      "code": "63-EF11003-26",
      "price": 1.79,
      "originalPrice": 1.88
    },
    "13-EF12001-26": {
      "code": "63-EF12003-26",
      "price": 1.96,
      "originalPrice": 2.06
    },
    "13-EF13001-26": {
      "code": "63-EF13003-26",
      "price": 2.11,
      "originalPrice": 2.22
    },
    "13-EF14001-26": {
      "code": "63-EF14003-26",
      "price": 1.82,
      "originalPrice": 1.92
    },
    "13-EF15001-26": {
      "code": "63-EF15003-26",
      "price": 1.96,
      "originalPrice": 2.06
    },
    "13-EF16001-26": {
      "code": "63-EF16003-26",
      "price": 2.11,
      "originalPrice": 2.22
    },
    "13-FCE10-26": {
      "code": "63-FCE103-26",
      "price": 1.29,
      "originalPrice": 1.36
    },
    "13-FCE20-26": {
      "code": "63-FCE203-26",
      "price": 1.41,
      "originalPrice": 1.48
    },
    "13-FCE30-26": {
      "code": "63-FCE303-26",
      "price": 1.54,
      "originalPrice": 1.62
    },
    "13-FCE40-26": {
      "code": "63-FCE403-26",
      "price": 1.7,
      "originalPrice": 1.79
    },
    "13-FCE50-26": {
      "code": "63-FCE503-26",
      "price": 1.52,
      "originalPrice": 1.6
    },
    "13-FCE60-26": {
      "code": "63-FCE603-26",
      "price": 1.65,
      "originalPrice": 1.74
    },
    "13-FCE70-26": {
      "code": "63-FCE703-26",
      "price": 1.81,
      "originalPrice": 1.91
    },
    "13-FCE80-26": {
      "code": "63-FCE803-26",
      "price": 1.67,
      "originalPrice": 1.76
    },
    "13-FCE90-26": {
      "code": "63-FCE903-26",
      "price": 1.81,
      "originalPrice": 1.91
    },
    "13-FCE100-26": {
      "code": "63-FCE1003-26",
      "price": 1.96,
      "originalPrice": 2.06
    },
    "13-FCE110-26": {
      "code": "63-FCE1103-26",
      "price": 2.02,
      "originalPrice": 2.13
    },
    "13-FCE120-26": {
      "code": "63-FCE1203-26",
      "price": 1.87,
      "originalPrice": 1.97
    },
    "13-FCE130-26": {
      "code": "63-FCE1303-26",
      "price": 2,
      "originalPrice": 2.11
    },
    "13-FCE140-26": {
      "code": "63-FCE1403-26",
      "price": 2.15,
      "originalPrice": 2.26
    },
    "13-FCE150-26": {
      "code": "63-FCE1503-26",
      "price": 2.2,
      "originalPrice": 2.32
    },
    "13-FCE257-26": {
      "code": "63-FCE257-26",
      "price": 1.33,
      "originalPrice": 1.4
    },
    "13-FCE557-26": {
      "code": "63-FCE557-26",
      "price": 1.44,
      "originalPrice": 1.52
    },
    "13-FCE657-26": {
      "code": "63-FCE657-26",
      "price": 1.59,
      "originalPrice": 1.67
    },
    "13-FCE757-26": {
      "code": "63-FCE757-26",
      "price": 1.53,
      "originalPrice": 1.61
    },
    "13-FCE817-26": {
      "code": "63-FCE817-26",
      "price": 1.56,
      "originalPrice": 1.64
    },
    "13-FCE827-26": {
      "code": "63-FCE827-26",
      "price": 1.7,
      "originalPrice": 1.79
    },
    "13-FCE837-26": {
      "code": "63-FCE837-26",
      "price": 1.72,
      "originalPrice": 1.81
    },
    "13-FCE957-26": {
      "code": "63-FCE957-26",
      "price": 1.87,
      "originalPrice": 1.97
    },
    "13-EO1002-26": {
      "code": "63-EO1003-26",
      "price": 1.72,
      "originalPrice": 1.81
    },
    "13-EO2002-26": {
      "code": "63-EO2003-26",
      "price": 1.82,
      "originalPrice": 1.92
    },
    "13-EO3002-26": {
      "code": "63-EO3003-26",
      "price": 1.94,
      "originalPrice": 2.04
    },
    "14-EC109-24": {
      "code": "63-EC109-24",
      "price": 1.84,
      "originalPrice": 1.88
    },
    "14-EC209-24": {
      "code": "63-EC209-24",
      "price": 2,
      "originalPrice": 2.04
    },
    "14-EC309-24": {
      "code": "63-EC309-24",
      "price": 2.12,
      "originalPrice": 2.16
    },
    "14-LC409-24": {
      "code": "63-LC409-24",
      "price": 2.39,
      "originalPrice": 2.43
    },
    "14-LC509-24": {
      "code": "63-LC509-24",
      "price": 2.48,
      "originalPrice": 2.52
    },
    "14-LC609-24": {
      "code": "63-LC609-24",
      "price": 2.83,
      "originalPrice": 2.87
    },
    "14-LC709-24": {
      "code": "63-LC709-24",
      "price": 3.05,
      "originalPrice": 3.09
    },
    "14-LC809-24": {
      "code": "63-LC809-24",
      "price": 3.24,
      "originalPrice": 3.28
    },
    "13-CORE101-26": {
      "code": "63-CORE103-26",
      "price": 1.1,
      "originalPrice": 1.16
    },
    "13-CORE201-26": {
      "code": "63-CORE203-26",
      "price": 1.15,
      "originalPrice": 1.21
    },
    "13-CORE301-26": {
      "code": "63-CORE303-26",
      "price": 1.16,
      "originalPrice": 1.22
    },
    "13-CORE401-26": {
      "code": "63-CORE403-26",
      "price": 1.19,
      "originalPrice": 1.25
    },
    "13-CORE501-26": {
      "code": "63-CORE503-26",
      "price": 1.24,
      "originalPrice": 1.31
    },
    "13-CORE601-26": {
      "code": "63-CORE603-26",
      "price": 1.31,
      "originalPrice": 1.38
    },
    "13-CORE701-26": {
      "code": "63-CORE703-26",
      "price": 1.35,
      "originalPrice": 1.42
    },
    "13-CORE801-26": {
      "code": "63-CORE803-26",
      "price": 1.44,
      "originalPrice": 1.52
    },
    "13-SFC17-26": {
      "code": "63-SFC17-26",
      "price": 3.74,
      "originalPrice": 3.94
    },
    "13-SFC27-26": {
      "code": "63-SFC27-26",
      "price": 4.02,
      "originalPrice": 4.23
    },
    "13-SFC37-26": {
      "code": "63-SFC37-26",
      "price": 4.32,
      "originalPrice": 4.55
    },
    "13-SFC47-26": {
      "code": "63-SFC47-26",
      "price": 3.78,
      "originalPrice": 3.98
    },
    "13-SFC57-26": {
      "code": "63-SFC57-26",
      "price": 4.05,
      "originalPrice": 4.26
    },
    "13-SFC67-26": {
      "code": "63-SFC67-26",
      "price": 4.35,
      "originalPrice": 4.58
    },
    "13-SFC77-26": {
      "code": "63-SFC77-26",
      "price": 3.9,
      "originalPrice": 4.11
    },
    "13-SFC87-26": {
      "code": "63-SFC87-26",
      "price": 4.2,
      "originalPrice": 4.42
    },
    "13-SFC97-26": {
      "code": "63-SFC97-26",
      "price": 4.49,
      "originalPrice": 4.73
    },
    "13-SFC107-26": {
      "code": "63-SFC107-26",
      "price": 4.12,
      "originalPrice": 4.34
    },
    "13-SFC117-26": {
      "code": "63-SFC117-26",
      "price": 4.32,
      "originalPrice": 4.55
    },
    "13-SFC127-26": {
      "code": "63-SFC127-26",
      "price": 4.63,
      "originalPrice": 4.87
    },
    "13-SFC137-26": {
      "code": "63-SFC137-26",
      "price": 4.88,
      "originalPrice": 5.14
    },
    "13-SFC147-26": {
      "code": "63-SFC147-26",
      "price": 5.71,
      "originalPrice": 6.01
    },
    "13-SFC157-26": {
      "code": "63-SFC157-26",
      "price": 6.1,
      "originalPrice": 6.42
    },
    "13-SFCC17-26": {
      "code": "63-SFCC17-26",
      "price": 3.51,
      "originalPrice": 3.69
    },
    "13-SFCC47-26": {
      "code": "63-SFCC47-26",
      "price": 3.81,
      "originalPrice": 4.01
    },
    "13-SFCC27-26": {
      "code": "63-SFCC27-26",
      "price": 4.09,
      "originalPrice": 4.31
    },
    "13-SFCC57-26": {
      "code": "63-SFCC57-26",
      "price": 3.55,
      "originalPrice": 3.74
    },
    "13-SFCC37-26": {
      "code": "63-SFCC37-26",
      "price": 3.83,
      "originalPrice": 4.03
    },
    "13-SFCC67-26": {
      "code": "63-SFCC67-26",
      "price": 4.11,
      "originalPrice": 4.33
    },
    "3-SOC17-26": {
      "code": "63-SOC17-26",
      "price": 3.48,
      "originalPrice": 3.67
    },
    "13-SOC27-26": {
      "code": "63-SOC27-26",
      "price": 3.57,
      "originalPrice": 3.76
    },
    "13-SOC37-26": {
      "code": "63-SOC37-26",
      "price": 3.65,
      "originalPrice": 3.84
    },
    "13-LFC17-26": {
      "code": "63-LFC17-26",
      "price": 2.27,
      "originalPrice": 2.39
    },
    "13-LFC27-26": {
      "code": "63-LFC27-26",
      "price": 2.41,
      "originalPrice": 2.54
    },
    "13-LFC37-26": {
      "code": "63-LFC37-26",
      "price": 2.58,
      "originalPrice": 2.72
    },
    "13-LFC47-26": {
      "code": "63-LFC47-26",
      "price": 2.76,
      "originalPrice": 2.9
    },
    "13-LFC57-26": {
      "code": "63-LFC57-26",
      "price": 2.53,
      "originalPrice": 2.66
    },
    "13-LFC67-26": {
      "code": "63-LFC67-26",
      "price": 2.71,
      "originalPrice": 2.85
    },
    "13-LFC77-26": {
      "code": "63-LFC77-26",
      "price": 2.88,
      "originalPrice": 3.03
    },
    "13-LFC87-26": {
      "code": "63-LFC87-26",
      "price": 2.97,
      "originalPrice": 3.13
    },
    "13-LFC97-26": {
      "code": "63-LFC97-26",
      "price": 3.17,
      "originalPrice": 3.34
    },
    "13-LFC107-26": {
      "code": "63-LFC107-26",
      "price": 3.37,
      "originalPrice": 3.55
    },
    "13-LFC117-26": {
      "code": "63-LFC117-26",
      "price": 3.13,
      "originalPrice": 3.29
    },
    "13-LFC127-26": {
      "code": "63-LFC127-26",
      "price": 3.32,
      "originalPrice": 3.49
    },
    "13-LFC137-26": {
      "code": "63-LFC137-26",
      "price": 3.52,
      "originalPrice": 3.7
    },
    "13-LFCC17-26": {
      "code": "63-LFCC17-26",
      "price": 2.29,
      "originalPrice": 2.41
    },
    "13-LFCC27-26": {
      "code": "63-LFCC27-26",
      "price": 2.46,
      "originalPrice": 2.59
    },
    "13-LFCC37-26": {
      "code": "63-LFCC37-26",
      "price": 2.63,
      "originalPrice": 2.77
    },
    "13-LFCC47-26": {
      "code": "63-LFCC47-26",
      "price": 2.74,
      "originalPrice": 2.88
    },
    "13-LFCC77-26": {
      "code": "63-LFCC77-26",
      "price": 2.93,
      "originalPrice": 3.08
    },
    "13-LFCC57-26": {
      "code": "63-LFCC57-26",
      "price": 3.1,
      "originalPrice": 3.26
    },
    "13-LFCC87-26": {
      "code": "63-LFCC87-26",
      "price": 2.86,
      "originalPrice": 3.01
    },
    "13-LFCC67-26": {
      "code": "63-LFCC67-26",
      "price": 3.07,
      "originalPrice": 3.23
    },
    "13-LFCC97-26": {
      "code": "63-LFCC97-26",
      "price": 3.23,
      "originalPrice": 3.4
    },
    "13-LOC17-26": {
      "code": "63-LOC17-26",
      "price": 2.26,
      "originalPrice": 2.38
    },
    "13-LOC27-26": {
      "code": "63-LOC27-26",
      "price": 2.41,
      "originalPrice": 2.54
    },
    "13-LOC37-26": {
      "code": "63-LOC37-26",
      "price": 2.91,
      "originalPrice": 3.06
    },
    "13-LOC47-26": {
      "code": "63-LOC47-26",
      "price": 3.04,
      "originalPrice": 3.2
    },
    "13-EFC17-26": {
      "code": "63-EFC17-26",
      "price": 1.5,
      "originalPrice": 1.58
    },
    "13-EFC27-26": {
      "code": "63-EFC27-26",
      "price": 1.62,
      "originalPrice": 1.71
    },
    "13-EFC37-26": {
      "code": "63-EFC37-26",
      "price": 1.77,
      "originalPrice": 1.86
    },
    "13-EFC47-26": {
      "code": "63-EFC47-26",
      "price": 1.79,
      "originalPrice": 1.88
    },
    "13-EFC57-26": {
      "code": "63-EFC57-26",
      "price": 1.88,
      "originalPrice": 1.98
    },
    "13-EFC67-26": {
      "code": "63-EFC67-26",
      "price": 1.68,
      "originalPrice": 1.77
    },
    "13-EFC77-26": {
      "code": "63-EFC77-26",
      "price": 1.81,
      "originalPrice": 1.91
    },
    "13-EFC87-26": {
      "code": "63-EFC87-26",
      "price": 1.99,
      "originalPrice": 2.09
    },
    "13-EFC97-26": {
      "code": "63-EFC97-26",
      "price": 1.75,
      "originalPrice": 1.84
    },
    "13-EFC107-26": {
      "code": "63-EFC107-26",
      "price": 1.88,
      "originalPrice": 1.98
    },
    "13-EFC117-26": {
      "code": "63-EFC117-26",
      "price": 2.06,
      "originalPrice": 2.17
    },
    "13-EFC127-26": {
      "code": "63-EFC127-26",
      "price": 2.21,
      "originalPrice": 2.33
    },
    "13-EFC137-26": {
      "code": "63-EFC137-26",
      "price": 2.22,
      "originalPrice": 2.34
    },
    "13-EFC147-26": {
      "code": "63-EFC147-26",
      "price": 2.38,
      "originalPrice": 2.5
    },
    "13-EFC157-26": {
      "code": "63-EFC157-26",
      "price": 2.55,
      "originalPrice": 2.68
    },
    "13-EFCQ17-26": {
      "code": "63-EFCQ17-26",
      "price": 1.4,
      "originalPrice": 1.47
    },
    "13-EFCQ27-26": {
      "code": "63-EFCQ27-26",
      "price": 1.51,
      "originalPrice": 1.59
    },
    "13-EFCQ37-26": {
      "code": "63-EFCQ37-26",
      "price": 1.66,
      "originalPrice": 1.75
    },
    "13-EFCQ47-26": {
      "code": "63-EFCQ47-26",
      "price": 1.58,
      "originalPrice": 1.66
    },
    "13-EFCQ57-26": {
      "code": "63-EFCQ57-26",
      "price": 1.71,
      "originalPrice": 1.8
    },
    "13-EFCQ67-26": {
      "code": "63-EFCQ67-26",
      "price": 1.87,
      "originalPrice": 1.97
    },
    "13-EFCQ77-26": {
      "code": "63-EFCQ77-26",
      "price": 1.63,
      "originalPrice": 1.72
    },
    "13-EFCQ87-26": {
      "code": "63-EFCQ87-26",
      "price": 1.77,
      "originalPrice": 1.86
    },
    "13-EFCQ97-26": {
      "code": "63-EFCQ97-26",
      "price": 1.94,
      "originalPrice": 2.04
    },
    "13-EFCQ107-26": {
      "code": "63-EFCQ107-26",
      "price": 2.08,
      "originalPrice": 2.19
    },
    "13-EFCQ117-26": {
      "code": "63-EFCQ117-26",
      "price": 2.24,
      "originalPrice": 2.36
    },
    "13-EFCQ127-26": {
      "code": "63-EFCQ127-26",
      "price": 2.4,
      "originalPrice": 2.53
    },
    "13-EFCQ137-26": {
      "code": "63-EFCQ137-26",
      "price": 2.2,
      "originalPrice": 2.32
    },
    "13-EFCQ147-26": {
      "code": "63-EFCQ147-26",
      "price": 2.38,
      "originalPrice": 2.5
    },
    "13-EFCQ157-26": {
      "code": "63-EFCQ157-26",
      "price": 2.54,
      "originalPrice": 2.67
    },
    "13-EOC17-26": {
      "code": "63-EOC17-26",
      "price": 1.76,
      "originalPrice": 1.85
    },
    "13-EOC27-26": {
      "code": "63-EOC27-26",
      "price": 1.7,
      "originalPrice": 1.79
    },
    "13-EOC37-26": {
      "code": "63-EOC37-26",
      "price": 1.82,
      "originalPrice": 1.91
    },
    "13-EOC47-26": {
      "code": "63-EOC47-26",
      "price": 2.02,
      "originalPrice": 2.13
    },
    "13-EOC57-26": {
      "code": "63-EOC57-26",
      "price": 2.15,
      "originalPrice": 2.27
    },
    "13-SFO107-26": {
      "code": "63-SFO107-26",
      "price": 4.84,
      "originalPrice": 5.09
    },
    "13-SFO207-26": {
      "code": "63-SFO207-26",
      "price": 5.09,
      "originalPrice": 5.36
    },
    "13-SFO307-26": {
      "code": "63-SFO307-26",
      "price": 5.36,
      "originalPrice": 5.64
    },
    "13-SFO407-26": {
      "code": "63-SFO407-26",
      "price": 4.88,
      "originalPrice": 5.14
    },
    "13-SFO507-26": {
      "code": "63-SFO507-26",
      "price": 5.17,
      "originalPrice": 5.44
    },
    "13-SFO607-26": {
      "code": "63-SFO607-26",
      "price": 5.46,
      "originalPrice": 5.75
    },
    "13-SFO707-26": {
      "code": "63-SFO707-26",
      "price": 5,
      "originalPrice": 5.26
    },
    "13-SFO807-26": {
      "code": "63-SFO807-26",
      "price": 5.27,
      "originalPrice": 5.55
    },
    "13-SFO907-26": {
      "code": "63-SFO907-26",
      "price": 5.57,
      "originalPrice": 5.86
    },
    "13-SFO1007-26": {
      "code": "63-SFO1007-26",
      "price": 5.04,
      "originalPrice": 5.3
    },
    "13-SFO1107-26": {
      "code": "63-SFO1107-26",
      "price": 5.3,
      "originalPrice": 5.58
    },
    "13-SFO1207-26": {
      "code": "63-SFO1207-26",
      "price": 5.61,
      "originalPrice": 5.91
    },
    "13-SFO1307-26": {
      "code": "63-SFO1307-26",
      "price": 5.06,
      "originalPrice": 5.33
    },
    "13-SFO1407-26": {
      "code": "63-SFO1407-26",
      "price": 5.34,
      "originalPrice": 5.62
    },
    "13-SFO1507-26": {
      "code": "63-SFO1507-26",
      "price": 5.77,
      "originalPrice": 6.07
    },
    "13-SFO1607-26": {
      "code": "63-SFO1607-26",
      "price": 5.83,
      "originalPrice": 6.14
    },
    "13-SFCO107-26": {
      "code": "63-SFCO107-26",
      "price": 4.53,
      "originalPrice": 4.77
    },
    "13-SFCO207-26": {
      "code": "63-SFCO207-26",
      "price": 4.76,
      "originalPrice": 5.01
    },
    "13-SFCO307-26": {
      "code": "63-SFCO307-26",
      "price": 5.04,
      "originalPrice": 5.3
    },
    "13-SFCO407-26": {
      "code": "63-SFCO407-26",
      "price": 4.59,
      "originalPrice": 4.83
    },
    "13-SFCO507-26": {
      "code": "63-SFCO507-26",
      "price": 4.83,
      "originalPrice": 5.08
    },
    "13-SFCO607-26": {
      "code": "63-SFCO607-26",
      "price": 5.09,
      "originalPrice": 5.36
    },
    "13-SFSA17-26": {
      "code": "63-SFSA17-26",
      "price": 4.04,
      "originalPrice": 4.25
    },
    "13-SFSA27-26": {
      "code": "63-SFSA27-26",
      "price": 4.16,
      "originalPrice": 4.38
    },
    "13-SFSA37-26": {
      "code": "63-SFSA37-26",
      "price": 4.37,
      "originalPrice": 4.6
    },
    "13-LFO107-26": {
      "code": "63-LFO107-26",
      "price": 2.41,
      "originalPrice": 2.54
    },
    "13-LFO207-26": {
      "code": "63-LFO207-26",
      "price": 2.5,
      "originalPrice": 2.63
    },
    "13-LFO307-26": {
      "code": "63-LFO307-26",
      "price": 2.76,
      "originalPrice": 2.91
    },
    "13-LFO407-26": {
      "code": "63-LFO407-26",
      "price": 2.91,
      "originalPrice": 3.06
    },
    "13-LFO507-26": {
      "code": "63-LFO507-26",
      "price": 2.97,
      "originalPrice": 3.13
    },
    "13-LFO607-26": {
      "code": "63-LFO607-26",
      "price": 3.12,
      "originalPrice": 3.28
    },
    "13-LFO707-26": {
      "code": "63-LFO707-26",
      "price": 3.26,
      "originalPrice": 3.43
    },
    "13-LFO807-26": {
      "code": "63-LFO807-26",
      "price": 3.63,
      "originalPrice": 3.82
    },
    "13-LFO907-26": {
      "code": "63-LFO907-26",
      "price": 3.79,
      "originalPrice": 3.99
    },
    "13-LFO1007-26": {
      "code": "63-LFO1007-26",
      "price": 3.94,
      "originalPrice": 4.15
    },
    "13-LFO1107-26": {
      "code": "63-LFO1107-26",
      "price": 3.95,
      "originalPrice": 4.16
    },
    "13-LFO1207-26": {
      "code": "63-LFO1207-26",
      "price": 4.12,
      "originalPrice": 4.34
    },
    "13-LFO1307-26": {
      "code": "63-LFO1307-26",
      "price": 4.3,
      "originalPrice": 4.53
    },
    "13-LFCO107-26": {
      "code": "63-LFCO107-26",
      "price": 3.25,
      "originalPrice": 3.42
    },
    "13-LFCO207-26": {
      "code": "63-LFCO207-26",
      "price": 3.4,
      "originalPrice": 3.58
    },
    "13-LFCO307-26": {
      "code": "63-LFCO307-26",
      "price": 3.55,
      "originalPrice": 3.74
    },
    "13-LFCO407-26": {
      "code": "63-LFCO407-26",
      "price": 3.63,
      "originalPrice": 3.82
    },
    "13-LFCO507-26": {
      "code": "63-LFCO507-26",
      "price": 3.79,
      "originalPrice": 3.99
    },
    "13-LFSA17-26": {
      "code": "63-LFSA17-26",
      "price": 2.32,
      "originalPrice": 2.44
    },
    "13-LFSA27-26": {
      "code": "63-LFSA27-26",
      "price": 2.43,
      "originalPrice": 2.56
    },
    "13-LFSA37-26": {
      "code": "63-LFSA37-26",
      "price": 2.68,
      "originalPrice": 2.82
    },
    "13-LFSA47-26": {
      "code": "63-LFSA47-26",
      "price": 2.78,
      "originalPrice": 2.93
    },
    "13-LFSA57-26": {
      "code": "63-LFSA57-26",
      "price": 2.9,
      "originalPrice": 3.05
    },
    "13-LFSA67-26": {
      "code": "63-LFSA67-26",
      "price": 3.04,
      "originalPrice": 3.2
    },
    "13-LFSA77-26": {
      "code": "63-LFSA77-26",
      "price": 2.9,
      "originalPrice": 3.05
    },
    "13-LFSA87-26": {
      "code": "63-LFSA87-26",
      "price": 3,
      "originalPrice": 3.16
    },
    "13-LFSA97-26": {
      "code": "63-LFSA97-26",
      "price": 3.14,
      "originalPrice": 3.31
    },
    "13-LFSA107-26": {
      "code": "63-LFSA107-26",
      "price": 3.43,
      "originalPrice": 3.61
    },
    "13-LFSA117-26": {
      "code": "63-LFSA117-26",
      "price": 3.53,
      "originalPrice": 3.72
    },
    "13-LFSA127-26": {
      "code": "63-LFSA127-26",
      "price": 3.7,
      "originalPrice": 3.89
    },
    "13-EFO107-26": {
      "code": "63-EFO107-26",
      "price": 1.73,
      "originalPrice": 1.82
    },
    "13-EFO207-26": {
      "code": "63-EFO207-26",
      "price": 1.82,
      "originalPrice": 1.92
    },
    "13-EFO307-26": {
      "code": "63-EFO307-26",
      "price": 1.95,
      "originalPrice": 2.05
    },
    "13-EFO407-26": {
      "code": "63-EFO407-26",
      "price": 1.82,
      "originalPrice": 1.92
    },
    "13-EFO507-26": {
      "code": "63-EFO507-26",
      "price": 1.92,
      "originalPrice": 2.02
    },
    "13-EFO607-26": {
      "code": "63-EFO607-26",
      "price": 2.05,
      "originalPrice": 2.16
    },
    "13-EFO707-26": {
      "code": "63-EFO707-26",
      "price": 1.86,
      "originalPrice": 1.96
    },
    "13-EFO807-26": {
      "code": "63-EFO807-26",
      "price": 1.95,
      "originalPrice": 2.05
    },
    "13-EFO907-26": {
      "code": "63-EFO907-26",
      "price": 2.08,
      "originalPrice": 2.19
    },
    "13-EFO1007-26": {
      "code": "63-EFO1007-26",
      "price": 2.26,
      "originalPrice": 2.38
    },
    "13-EFO1107-26": {
      "code": "63-EFO1107-26",
      "price": 2.33,
      "originalPrice": 2.45
    },
    "13-EFO1207-26": {
      "code": "63-EFO1207-26",
      "price": 2.47,
      "originalPrice": 2.6
    },
    "13-EFSA17-26": {
      "code": "63-EFSA17-26",
      "price": 1.77,
      "originalPrice": 1.86
    },
    "13-EFSA27-26": {
      "code": "63-EFSA27-26",
      "price": 1.88,
      "originalPrice": 1.98
    },
    "13-EFSA37-26": {
      "code": "63-EFSA37-26",
      "price": 2.02,
      "originalPrice": 2.13
    },
    "13-EFSA47-26": {
      "code": "63-EFSA47-26",
      "price": 1.87,
      "originalPrice": 1.97
    },
    "13-EFSA57-26": {
      "code": "63-EFSA57-26",
      "price": 2,
      "originalPrice": 2.1
    },
    "13-EFSA67-26": {
      "code": "63-EFSA67-26",
      "price": 2.13,
      "originalPrice": 2.24
    },
    "13-FCL1357-26": {
      "code": "63-FCL1357-26",
      "price": 2.38,
      "originalPrice": 2.5
    },
    "13-FCL1367-26": {
      "code": "63-FCL1367-26",
      "price": 2.56,
      "originalPrice": 2.69
    },
    "13-SFS17-26": {
      "code": "63-SFS17-26",
      "price": 3.52,
      "originalPrice": 3.7
    },
    "13-SFS27-26": {
      "code": "63-SFS27-26",
      "price": 3.75,
      "originalPrice": 3.95
    },
    "13-SFS37-26": {
      "code": "63-SFS37-26",
      "price": 3.99,
      "originalPrice": 4.2
    },
    "13-SFS47-26": {
      "code": "63-SFS47-26",
      "price": 3.6,
      "originalPrice": 3.79
    },
    "13-SFS57-26": {
      "code": "63-SFS57-26",
      "price": 3.84,
      "originalPrice": 4.04
    },
    "13-SFS67-26": {
      "code": "63-SFS67-26",
      "price": 4.09,
      "originalPrice": 4.3
    },
    "13-SFS77-26": {
      "code": "63-SFS77-26",
      "price": 3.7,
      "originalPrice": 3.89
    },
    "13-SFS87-26": {
      "code": "63-SFS87-26",
      "price": 3.92,
      "originalPrice": 4.13
    },
    "13-SFS97-26": {
      "code": "63-SFS97-26",
      "price": 4.18,
      "originalPrice": 4.4
    },
    "13-SFS107-26": {
      "code": "63-SFS107-26",
      "price": 4.05,
      "originalPrice": 4.26
    },
    "13-SFS117-26": {
      "code": "63-SFS117-26",
      "price": 4.24,
      "originalPrice": 4.46
    },
    "13-SFS127-26": {
      "code": "63-SFS127-26",
      "price": 4.48,
      "originalPrice": 4.72
    },
    "13-SFS137-26": {
      "code": "63-SFS137-26",
      "price": 4.16,
      "originalPrice": 4.38
    },
    "13-SFS147-26": {
      "code": "63-SFS147-26",
      "price": 4.34,
      "originalPrice": 4.57
    },
    "13-SFS157-26": {
      "code": "63-SFS157-26",
      "price": 4.6,
      "originalPrice": 4.84
    },
    "13-SFS167-26": {
      "code": "63-SFS167-26",
      "price": 4.25,
      "originalPrice": 4.47
    },
    "13-SFS177-26": {
      "code": "63-SFS177-26",
      "price": 4.44,
      "originalPrice": 4.67
    },
    "13-SFS187-26": {
      "code": "63-SFS187-26",
      "price": 4.89,
      "originalPrice": 5.15
    },
    "13-SFS197-26": {
      "code": "63-SFS197-26",
      "price": 5.25,
      "originalPrice": 5.53
    },
    "13-SFS207-26": {
      "code": "63-SFS207-26",
      "price": 5.64,
      "originalPrice": 5.94
    },
    "13-SFS217-26": {
      "code": "63-SFS217-26",
      "price": 5.81,
      "originalPrice": 6.12
    },
    "13-SFS227-26": {
      "code": "63-SFS227-26",
      "price": 5.96,
      "originalPrice": 6.27
    },
    "13-SFCS17-26": {
      "code": "63-SFCS17-26",
      "price": 3.54,
      "originalPrice": 3.73
    },
    "13-SFCS27-26": {
      "code": "63-SFCS27-26",
      "price": 3.74,
      "originalPrice": 3.94
    },
    "13-SFCS37-26": {
      "code": "63-SFCS37-26",
      "price": 3.96,
      "originalPrice": 4.17
    },
    "13-LFS17-26": {
      "code": "63-LFS17-26",
      "price": 2.04,
      "originalPrice": 2.15
    },
    "13-LFS27-26": {
      "code": "63-LFS27-26",
      "price": 2.19,
      "originalPrice": 2.3
    },
    "13-LFS37-26": {
      "code": "63-LFS37-26",
      "price": 2.52,
      "originalPrice": 2.65
    },
    "13-LFS47-26": {
      "code": "63-LFS47-26",
      "price": 2.38,
      "originalPrice": 2.5
    },
    "13-LFS57-26": {
      "code": "63-LFS57-26",
      "price": 2.54,
      "originalPrice": 2.67
    },
    "13-LFS67-26": {
      "code": "63-LFS67-26",
      "price": 2.69,
      "originalPrice": 2.83
    },
    "13-LFS77-26": {
      "code": "63-LFS77-26",
      "price": 2.55,
      "originalPrice": 2.68
    },
    "13-LFS87-26": {
      "code": "63-LFS87-26",
      "price": 2.72,
      "originalPrice": 2.86
    },
    "13-LFS97-26": {
      "code": "63-LFS97-26",
      "price": 2.86,
      "originalPrice": 3.01
    },
    "13-LFS107-26": {
      "code": "63-LFS107-26",
      "price": 2.89,
      "originalPrice": 3.04
    },
    "13-LFS117-26": {
      "code": "63-LFS117-26",
      "price": 3.06,
      "originalPrice": 3.22
    },
    "13-LFS127-26": {
      "code": "63-LFS127-26",
      "price": 3.22,
      "originalPrice": 3.39
    },
    "13-LFS137-26": {
      "code": "63-LFS137-26",
      "price": 3.12,
      "originalPrice": 3.28
    },
    "13-LFS147-26": {
      "code": "63-LFS147-26",
      "price": 3.3,
      "originalPrice": 3.47
    },
    "13-LFS157-26": {
      "code": "63-LFS157-26",
      "price": 3.48,
      "originalPrice": 3.66
    },
    "13-LFCS17-26": {
      "code": "63-LFCS17-26",
      "price": 2.22,
      "originalPrice": 2.34
    },
    "13-LFCS27-26": {
      "code": "63-LFCS27-26",
      "price": 2.38,
      "originalPrice": 2.5
    },
    "13-LFCS37-26": {
      "code": "63-LFCS37-26",
      "price": 2.53,
      "originalPrice": 2.66
    },
    "13-LFCS47-26": {
      "code": "63-LFCS47-26",
      "price": 2.4,
      "originalPrice": 2.53
    },
    "13-LFCS57-26": {
      "code": "63-LFCS57-26",
      "price": 2.55,
      "originalPrice": 2.68
    },
    "13-LFCS67-26": {
      "code": "63-LFCS67-26",
      "price": 2.72,
      "originalPrice": 2.86
    },
    "13-LFCS77-26": {
      "code": "63-LFCS77-26",
      "price": 2.95,
      "originalPrice": 3.1
    },
    "13-LFCS87-26": {
      "code": "63-LFCS87-26",
      "price": 3.12,
      "originalPrice": 3.28
    },
    "13-LFCS97-26": {
      "code": "63-LFCS97-26",
      "price": 3.22,
      "originalPrice": 3.39
    },
    "13-EFS17-26": {
      "code": "63-EFS17-26",
      "price": 1.44,
      "originalPrice": 1.52
    },
    "13-EFS27-26": {
      "code": "63-EFS27-26",
      "price": 1.56,
      "originalPrice": 1.64
    },
    "13-EFS37-26": {
      "code": "63-EFS37-26",
      "price": 1.66,
      "originalPrice": 1.75
    },
    "13-EFS47-26": {
      "code": "63-EFS47-26",
      "price": 1.8,
      "originalPrice": 1.89
    },
    "13-EFS57-26": {
      "code": "63-EFS57-26",
      "price": 1.59,
      "originalPrice": 1.67
    },
    "13-EFS67-26": {
      "code": "63-EFS67-26",
      "price": 1.7,
      "originalPrice": 1.79
    },
    "13-EFS77-26": {
      "code": "63-EFS77-26",
      "price": 1.83,
      "originalPrice": 1.93
    },
    "13-EFS87-26": {
      "code": "63-EFS87-26",
      "price": 1.69,
      "originalPrice": 1.78
    },
    "13-EFS97-26": {
      "code": "63-EFS97-26",
      "price": 1.8,
      "originalPrice": 1.89
    },
    "13-EFS107-26": {
      "code": "63-EFS107-26",
      "price": 1.94,
      "originalPrice": 2.04
    },
    "13-EFS117-26": {
      "code": "63-EFS117-26",
      "price": 1.82,
      "originalPrice": 1.92
    },
    "13-EFS127-26": {
      "code": "63-EFS127-26",
      "price": 1.93,
      "originalPrice": 2.03
    },
    "13-EFS137-26": {
      "code": "63-EFS137-26",
      "price": 2.07,
      "originalPrice": 2.18
    },
    "13-EFS147-26": {
      "code": "63-EFS147-26",
      "price": 1.92,
      "originalPrice": 2.02
    },
    "13-EFS157-26": {
      "code": "63-EFS157-26",
      "price": 2.02,
      "originalPrice": 2.13
    },
    "13-EFS167-26": {
      "code": "63-EFS167-26",
      "price": 2.17,
      "originalPrice": 2.28
    },
    "13-SFN17-26": {
      "code": "63-SFN17-26",
      "price": 3.22,
      "originalPrice": 3.39
    },
    "13-SFN27-26": {
      "code": "63-SFN27-26",
      "price": 3.52,
      "originalPrice": 3.7
    },
    "13-SFN37-26": {
      "code": "63-SFN37-26",
      "price": 3.84,
      "originalPrice": 4.04
    },
    "13-SFN47-26": {
      "code": "63-SFN47-26",
      "price": 3.41,
      "originalPrice": 3.59
    },
    "13-SFN57-26": {
      "code": "63-SFN57-26",
      "price": 3.67,
      "originalPrice": 3.86
    },
    "13-SFN67-26": {
      "code": "63-SFN67-26",
      "price": 3.99,
      "originalPrice": 4.2
    },
    "13-SFN77-26": {
      "code": "63-SFN77-26",
      "price": 3.88,
      "originalPrice": 4.08
    },
    "13-SFN87-26": {
      "code": "63-SFN87-26",
      "price": 4.15,
      "originalPrice": 4.37
    },
    "13-SFN97-26": {
      "code": "63-SFN97-26",
      "price": 4.47,
      "originalPrice": 4.71
    },
    "13-SFN107-26": {
      "code": "63-SFN107-26",
      "price": 4.07,
      "originalPrice": 4.28
    },
    "13-SFN117-26": {
      "code": "63-SFN117-26",
      "price": 4.39,
      "originalPrice": 4.62
    },
    "13-SFN127-26": {
      "code": "63-SFN127-26",
      "price": 4.85,
      "originalPrice": 5.1
    },
    "13-SFN137-26": {
      "code": "63-SFN137-26",
      "price": 4.64,
      "originalPrice": 4.88
    },
    "13-SFN147-26": {
      "code": "63-SFN147-26",
      "price": 5.06,
      "originalPrice": 5.33
    },
    "13-SFN157-26": {
      "code": "63-SFN157-26",
      "price": 5.53,
      "originalPrice": 5.82
    },
    "13-SFN167-26": {
      "code": "63-SFN167-26",
      "price": 5.72,
      "originalPrice": 6.02
    },
    "13-SFN177-26": {
      "code": "63-SFN177-26",
      "price": 5.91,
      "originalPrice": 6.22
    },
    "13-LFN17-26": {
      "code": "63-LFN17-26",
      "price": 2.01,
      "originalPrice": 2.12
    },
    "13-LFN27-26": {
      "code": "63-LFN27-26",
      "price": 2.17,
      "originalPrice": 2.28
    },
    "13-LFN37-26": {
      "code": "63-LFN37-26",
      "price": 2.33,
      "originalPrice": 2.45
    },
    "13-LFN47-26": {
      "code": "63-LFN47-26",
      "price": 2.49,
      "originalPrice": 2.62
    },
    "13-LFN57-26": {
      "code": "63-LFN57-26",
      "price": 2.31,
      "originalPrice": 2.43
    },
    "13-LFN67-26": {
      "code": "63-LFN67-26",
      "price": 2.47,
      "originalPrice": 2.6
    },
    "13-LFN77-26": {
      "code": "63-LFN77-26",
      "price": 2.62,
      "originalPrice": 2.76
    },
    "13-LFN87-26": {
      "code": "63-LFN87-26",
      "price": 2.5,
      "originalPrice": 2.63
    },
    "13-LFN97-26": {
      "code": "63-LFN97-26",
      "price": 2.63,
      "originalPrice": 2.77
    },
    "13-LFN107-26": {
      "code": "63-LFN107-26",
      "price": 2.8,
      "originalPrice": 2.95
    },
    "13-LFN117-26": {
      "code": "63-LFN117-26",
      "price": 2.58,
      "originalPrice": 2.72
    },
    "13-LFN127-26": {
      "code": "63-LFN127-26",
      "price": 2.78,
      "originalPrice": 2.93
    },
    "13-LFN137-26": {
      "code": "63-LFN137-26",
      "price": 3.01,
      "originalPrice": 3.17
    },
    "13-LFCN17-26": {
      "code": "63-LFCN17-26",
      "price": 2.34,
      "originalPrice": 2.46
    },
    "13-LFCN27-26": {
      "code": "63-LFCN27-26",
      "price": 2.5,
      "originalPrice": 2.63
    },
    "13-LFCN37-26": {
      "code": "63-LFCN37-26",
      "price": 2.66,
      "originalPrice": 2.8
    },
    "13-LFCN47-26": {
      "code": "63-LFCN47-26",
      "price": 2.42,
      "originalPrice": 2.55
    },
    "13-LFCN57-26": {
      "code": "63-LFCN57-26",
      "price": 2.58,
      "originalPrice": 2.72
    },
    "13-LFCN67-26": {
      "code": "63-LFCN67-26",
      "price": 2.75,
      "originalPrice": 2.89
    },
    "13-LFCN77-26": {
      "code": "63-LFCN77-26",
      "price": 2.56,
      "originalPrice": 2.69
    },
    "13-LFCN87-26": {
      "code": "63-LFCN87-26",
      "price": 2.72,
      "originalPrice": 2.86
    },
    "13-LFCN97-26": {
      "code": "63-LFCN97-26",
      "price": 2.93,
      "originalPrice": 3.08
    },
    "13-EFN17-26": {
      "code": "63-EFN17-26",
      "price": 1.43,
      "originalPrice": 1.5
    },
    "13-EFN27-26": {
      "code": "63-EFN27-26",
      "price": 1.54,
      "originalPrice": 1.62
    },
    "13-EFN37-26": {
      "code": "63-EFN37-26",
      "price": 1.69,
      "originalPrice": 1.78
    },
    "13-EFN47-26": {
      "code": "63-EFN47-26",
      "price": 1.51,
      "originalPrice": 1.59
    },
    "13-EFN57-26": {
      "code": "63-EFN57-26",
      "price": 1.62,
      "originalPrice": 1.71
    },
    "13-EFN67-26": {
      "code": "63-EFN67-26",
      "price": 1.78,
      "originalPrice": 1.87
    },
    "13-EFN77-26": {
      "code": "63-EFN77-26",
      "price": 1.61,
      "originalPrice": 1.69
    },
    "13-EFN87-26": {
      "code": "63-EFN87-26",
      "price": 1.73,
      "originalPrice": 1.82
    },
    "13-EFN97-26": {
      "code": "63-EFN97-26",
      "price": 1.89,
      "originalPrice": 1.99
    },
    "13-EFN107-26": {
      "code": "63-EFN107-26",
      "price": 1.64,
      "originalPrice": 1.73
    },
    "13-EFN117-26": {
      "code": "63-EFN117-26",
      "price": 1.78,
      "originalPrice": 1.87
    },
    "13-EFN127-26": {
      "code": "63-EFN127-26",
      "price": 1.94,
      "originalPrice": 2.04
    },
    "13-EFN137-26": {
      "code": "63-EFN137-26",
      "price": 1.7,
      "originalPrice": 1.79
    },
    "13-EFN147-26": {
      "code": "63-EFN147-26",
      "price": 1.83,
      "originalPrice": 1.93
    },
    "13-EFN157-26": {
      "code": "63-EFN157-26",
      "price": 2,
      "originalPrice": 2.11
    }
  }
};
